---
- name: Run path.sh across all hosts
  hosts: all
  become: true

  # No hard‑coded secrets. These variables will be set at launch
  # via the AWX Survey (prompt type “Password” for couch_pass).
  #   – couch_user
  #   – couch_pass

  vars:
    ubuntu_home: "/home/ubuntu"
    COUCHBIN="{{ couch }}"

  tasks:
    - name: Copy path.sh to ubuntu's home directory
      copy:
        src: "{{ playbook_dir }}/path.sh"
        dest: "{{ ubuntu_home }}/path.sh"
        mode: "0755"
        owner: ubuntu
        group: ubuntu

    - name: Run path.sh script as ubuntu user, injecting DB creds
      become_user: ubuntu
      shell: ./path.sh > path.txt
      args:
        chdir: "{{ ubuntu_home }}"
      environment:
        COUCH_USER: "{{ couch_user }}"
        COUCH_PASS: "{{ couch_pass }}"

    - name: Read path.txt contents
      slurp:
        src: "{{ ubuntu_home }}/path.txt"
      register: path_file_content

    - name: Print path.txt contents
      debug:
        # Assumes path.txt does NOT contain passwords.
        msg: "{{ path_file_content.content | b64decode }}"

    
