---
- name: Couchbase corruption scan (local node)
  hosts: all
  gather_facts: false

  vars:
    script_name: path.sh
    ubuntu_home: "/home/ubuntu"     # adjust if the home dir differs

  tasks:

    # 1 ▸ Copy the script to the remote node
    - name: Copy {{ script_name }} to ubuntu's home
      copy:
        src: "{{ playbook_dir }}/{{ script_name }}"
        dest: "{{ ubuntu_home }}/{{ script_name }}"
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    # 2 ▸ Ensure the script is executable (belt-and-braces)
    - name: Make {{ script_name }} executable
      become: true
      file:
        path: "{{ ubuntu_home }}/{{ script_name }}"
        mode: "0755"
        owner: ubuntu
        group: ubuntu

    # 3 ▸ Run the script with the flag chosen in the AWX survey
    - name: Run {{ script_name }} with chosen flag
      become: true
      become_user: ubuntu
      shell: |
        ./{{ script_name }} --{{ scan_flag | default('both') }} \
          > path.txt 2>&1
      args:
        chdir: "{{ ubuntu_home }}"
      environment:
        CB_USER: "{{ couch_user }}"
        CB_PASS: "{{ couch_pass }}"

    # 4 ▸ Extract last 10 lines of output to path2.txt
    - name: Extract last 10 lines of path.txt to path2.txt
      become: true
      become_user: ubuntu
      shell: tail -n 10 path.txt > path2.txt
      args:
        chdir: "{{ ubuntu_home }}"

    # 5 ▸ Read the output from path2.txt into a variable
    - name: Read path2.txt content
      become: true
      become_user: ubuntu
      shell: cat path2.txt
      args:
        chdir: "{{ ubuntu_home }}"
      register: path2_output

    # 6 ▸ Print first 20 lines of script output to terminal
    - name: Print first 20 lines of script output
      debug:
        msg: "{{ path2_output.stdout_lines[:-1] }}"
