---
- name: Run path.sh across all hosts
  hosts: all
  become: true

  vars:
    USER: "{{ couch_user }}"
    PASS: "{{ couch_pass }}"
    ubuntu_home: "/home/ubuntu"

  tasks:
    - name: Copy path.sh to ubuntu's home directory
      copy:
        src: "{{ playbook_dir }}/path.sh"
        dest: "{{ ubuntu_home }}/path.sh"
        mode: "0755"
        owner: ubuntu
        group: ubuntu

    - name: Run path.sh script as ubuntu user
      become_user: ubuntu
      shell: |
        ./path.sh > path.txt
      args:
        chdir: "{{ ubuntu_home }}"

    - name: Read path.txt contents
      slurp:
        src: "{{ ubuntu_home }}/path.txt"
      register: path_file_content

    - name: Print path.txt contents
      debug:
        path_lines: "{{ path_file_content.content | b64decode  }}"
