---
- name: Couchbase corruption scan (local node)
  hosts: all
  gather_facts: false

  vars:
    script_name: path.sh
    ubuntu_home: "/home/ubuntu"     # adjust if the home dir differs

  tasks:

    # 1 ▸ Copy the script to the remote node
    - name: Copy {{ script_name }} to ubuntu's home
      copy:
        src: "{{ playbook_dir }}/{{ script_name }}"
        dest: "{{ ubuntu_home }}/{{ script_name }}"
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    # 2 ▸ Ensure the script is executable (belt-and-braces)
    - name: Make {{ script_name }} executable
      become: true
      file:
        path: "{{ ubuntu_home }}/{{ script_name }}"
        mode: "0755"
        owner: ubuntu
        group: ubuntu

    # 3 ▸ Run the script with the flag chosen in the AWX survey
    - name: Run {{ script_name }} with chosen flag
      become: true
      become_user: ubuntu
      shell: |
        ./{{ script_name }} --{{ scan_flag | default('both') }} \
          > path.txt 2>&1
      args:
        chdir: "{{ ubuntu_home }}"
      environment:
        CB_USER: "{{ couch_user }}"
        CB_PASS: "{{ couch_pass }}"

    # 4 ▸ Display the output from path.txt (full content)
    - name: Show output from path.txt
      become: true
      become_user: ubuntu
      shell: cat path.txt
      args:
        chdir: "{{ ubuntu_home }}"
      register: path_output

    - name: Print script output
      debug:
        var: path_output.stdout_lines

    # 5 ▸ (Optional) Fetch the path.txt to the control node for complete logs
    - name: Fetch path.txt to control node
      become: true
      fetch:
        src: "{{ ubuntu_home }}/path.txt"
        dest: "./path_output/{{ inventory_hostname }}.txt"
        flat: yes
