---
- name: Couchbase corruption scan (local node)
  hosts: all         # inventory group with the target nodes
  gather_facts: false

  vars:
    script_name: path.sh
    ubuntu_home: "/home/ubuntu"     # adjust if the home dir differs

  tasks:

    # 1 ▸ Copy the script to the remote node
    - name: Copy {{ script_name }} to ubuntu's home
      copy:
        src: "{{ playbook_dir }}/{{ script_name }}"
        dest: "{{ ubuntu_home }}/{{ script_name }}"
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    # 2 ▸ Ensure the script is executable (belt-and-braces)
    - name: Make {{ script_name }} executable
      become: true
      file:
        path: "{{ ubuntu_home }}/{{ script_name }}"
        mode: "0755"
        owner: ubuntu
        group: ubuntu

    # 3 ▸ Run the script with the flag chosen in the AWX survey
    - name: Run {{ script_name }} with chosen flag
      become: true
      become_user: ubuntu
      shell: |
        ./{{ script_name }} --{{ scan_flag | default('both') }} \
          > path.txt
      args:
        chdir: "{{ ubuntu_home }}"
      environment:
        CB_USER: "{{ couch_user }}"
        CB_PASS: "{{ couch_pass }}"
