---
- name: Run path.sh across all hosts
  hosts: all
  become: true

  vars:
    HOST: "{{ couch_host }}"
    PORT: "{{ couch_port }}"
    USER: "{{ couch_user }}"
    PASS: "{{ couch_pass }}"

  tasks:
    
    - name: Copy path.sh to $HOME
      copy:
        src: "{{ playbook_dir }}/path.sh"
        dest: "$HOME"/path.sh"  # still explicit path for reliability
        mode: "0755"
        owner: ubuntu
        group: ubuntu

    
    - name: Run path.sh script once
      become_user: ubuntu
      shell: |
        "$HOME"/path.sh > "$HOME"/path.txt
      args:
        chdir: "$HOME"
