---
- name: Script to Run couch_check_all.sh
  hosts: all
  become: yes
  vars: 
    HOST: "{{ couch_host }}"
    PORT: "{{ couch_port }}"
    USER: "{{ couch_user }}"
    PASS: "{{ couch_pass }}"

  tasks:

    - name: Ensure /home/ubuntu directory exists
      file:
        path: /home/ubuntu
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy path.sh to /home/ubuntu
      copy:
        src: "{{ playbook_dir }}/path.sh"
        dest: /home/ubuntu/path.sh
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Run path.sh script once as ubuntu user
      shell: ./path.sh > path.txt
      args:
        chdir: /home/ubuntu
      become_user: ubuntu
