---
- name: Run path.sh across all hosts
  hosts: all
  become: true

  vars:
    USER: "{{ couch_user }}"
    PASS: "{{ couch_pass }}"

  tasks:
    - name: Copy path.sh to user's home directory
      copy:
        src: "{{ playbook_dir }}/path.sh"
        dest: "{{ ansible_env.HOME }}/path.sh"  # reliably get home directory
        mode: "0755"
        owner: ubuntu
        group: ubuntu

    - name: Run path.sh script once
      become_user: ubuntu
      shell: |
        ./path.sh > path.txt
      args:
        chdir: "{{ ansible_env.HOME }}"
