---
- name: Copy and run monitor.sh on the worker node
  hosts: all
  become: yes
  vars: {}

  tasks:
    - name: Copy couch_check_all.sh to /home/ubuntu
      copy:
        src: "{{ playbook_dir }}/couch_check_all.sh"
        dest: /home/ubuntu/couch_check_all.sh
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Copy path.sh to /home/ubuntu
      copy:
        src: "{{ playbook_dir }}/path.sh"
        dest: /home/ubuntu/path.sh
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Run path.sh script once
      shell: /home/ubuntu/path.sh > /home/ubuntu/path.txt
      args:
        chdir: /home/ubuntu
      become_user: ubuntu

    - name: Copy env.sh to /home/ubuntu
      copy:
        src: "{{ playbook_dir }}/env.sh"
        dest: /home/ubuntu/env.sh
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Run env.sh script once
      shell: /home/ubuntu/env.sh >  /home/ubuntu/env.txt
      args:
        chdir: /home/ubuntu
      become_user: ubuntu
