---
- name: Create EC2 Instances
  hosts:  localhost
  gather_facts: no

  vars:
    region: []
    key_name: []
    instance_type: []
    ami_id: []
    security_groups: []
    instance_count: []
    tag_name: []

  tasks:
    - name: Create EC2 instances
      ec2_instance:
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        security_groups: "{{ security_groups }}"
        network:
          assign_public_ip: true
        state: present
        tags:
          Name: "{{ tag_name }}"
      #loop: "{{ range(1, instance_count + 1) | list }}"
      register: ec2

    - name: Print instance details
      debug:
        msg: "Instance ID: {{ item.instance_id }}, Public IP: {{ item.public_ip_address | default('N/A') }}"
      loop: "{{ ec2.results | map(attribute='instances') | list | flatten }}"
      when: ec2.results is defined
