---
- name: Create EC2 Instances
  hosts: localhost
  gather_facts: no

  vars:
    region: []
    key_name: []
    instance_type: []
    ami_id: []
    security_groups: []
    instance_count: []
    tag_name: []

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        security_groups: "{{ security_groups }}"
        count: "{{ instance_count | int }}"
        network:
          assign_public_ip: true
        state: present
        tags:
          Name: "{{ tag_name }}"
      register: ec2

    - name: Print instance details
      debug:
        msg: "Instance ID: {{ item.instance_id }}, Public IP: {{ item.public_ip_address | default('N/A') }}"
      loop: "{{ ec2.instances }}"
      when: ec2.instances is defined

    - name: Debug ec2 structure (if troubleshooting is required)
      debug:
        var: ec2
