---
- name: Create EC2 Instances
  hosts: all
  #connection: local
  #gather_facts: no

  vars_prompt:
    # - name: "instance_count"
    #   prompt: "Enter the number of instances to create"
    #   private: no

    # - name: "instance_type"
    #   prompt: "Enter the instance type (e.g., t2.micro)"
    #   private: no

    # - name: "ami_id"
    #   prompt: "Enter the AMI ID (e.g., ami-0abcdef1234567890)"
    #   private: no

    # - name: "key_name"
    #   prompt: "Enter the key pair name for SSH access"
    #   private: no

    # - name: "security_group"
    #   prompt: "Enter the security group name"
    #   private: no

    # - name: "region"
    #   prompt: "Enter the AWS region (e.g., ap-south-1)"
    #   private: no

    # - name: "tag_name"
    #   prompt: "Enter the tag name for the instance"
    #   private: no

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        security_group: "{{ security_group }}"
        count: "{{ instance_count | int }}"
        network:
          assign_public_ip: true
        state: present
        tags:
          Name: "{{ tag_name }}"
      register: ec2

    - name: Print instance details
      debug:
        msg: "Instance ID: {{ item.instance_id }}, Public IP: {{ item.public_ip_address | default('N/A') }}"
      loop: "{{ ec2.instances }}"
      when: ec2.instances is defined

    - name: Debug ec2 structure (if troubleshooting is required)
      debug:
        var: ec2
