- name: Launch an EC2 instance on AWS
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create an EC2 key pair
      amazon.aws.ec2_key:
        name: my-key-pair
        region: us-east-1
      register: key_pair
      delegate_to: localhost

    - name: Save private key
      copy:
        content: "{{ key_pair.key.private_key }}"
        dest: "./my-key-pair.pem"
        mode: '0600'
      when: key_pair.changed
      delegate_to: localhost

    - name: Create a security group
      amazon.aws.ec2_group:
        name: my-security-group
        description: Allow SSH and HTTP
        region: us-east-1
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
              - 443
              - 8091
            cidr_ip: 0.0.0.0/0
      register: security_group
      delegate_to: localhost

    - name: Launch an EC2 instance
      amazon.aws.ec2_instance:
        name: my-ec2-instance
        key_name: my-key-pair
        instance_type: t2.medium
        security_groups: ["my-security-group"]
        image_id: ami-08b5b3a93ed654d19
        region: us-east-1
        wait: yes
        count: 1
        network:
          assign_public_ip: yes
      register: ec2_instance
      delegate_to: localhost

    - name: Tag the EC2 instance
      amazon.aws.ec2_tag:
        region: us-east-1
        resource: "{{ ec2_instance.instances[0].instance_id }}"
        tags:
          Name: my-ec2-instance
          Environment: Dev
      delegate_to: localhost
