---
- name: Manage Couchbase indexes couchbase
  hosts: all
  become: yes
  tasks:
    - name: Ensure jq is installed
      apt:
        name: jq
        state: present
        update_cache: yes

    - name: Validate index file existence
      ansible.builtin.stat:
        path: /home/ubuntu/index_file.txt
      register: index_file_stat

    - name: Read and decode index file
      ansible.builtin.slurp:
        src: /home/ubuntu/index_file.txt
      register: index_file_content

    - name: Decode the index file content
      set_fact:
        decoded_index_file_content: "{{ index_file_content.content | b64decode }}"

    - name: Debug decoded index file content
      debug:
        msg: "{{ decoded_index_file_content }}"

    - name: Extract index components for building
      set_fact:
        index_components: "{{ decoded_index_file_content | regex_findall('CREATE INDEX `([^`]+)` ON `([^`]+)`\\.([^`]+)\\.([^`]+)\\(([^)]+)\\);') }}"

    - name: Debug index creation statements
      debug:
        msg: "{{ index_creation_statements }}"

    - name: Validate Couchbase CLI availability
      shell: "/opt/couchbase/bin/cbq --version"
      register: cbq_check
      changed_when: false

    - name: Create indexes
      shell: "/opt/couchbase/bin/cbq -u Admin -p redhat -s '{{ item }}'"
      with_items: "{{ index_creation_statements }}"
      ignore_errors: true
      register: ddl_output

    - name: Extract bucket, scope, collection, and index names
      set_fact:
        index_components: "{{ decoded_index_file_content | regex_findall('CREATE INDEX `([^`]+)` ON `([^`]+)`\\.([^`]+)\\.([^`]+)\\(([^)]+)\\);') }}"

    - name: Debug index components
      debug:
        msg: "{{ index_components }}"

    - name: Combine index names for BUILD INDEX command
      set_fact:
        index_build_command: |
          BUILD INDEX ON `{{ index_components[0][1] }}`.`{{ index_components[0][2] }}`.`{{ index_components[0][3] }}`
          ({{ index_components | map(attribute='0') | join(', ') }});
      
    - name: Debug index build command
      debug:
        msg: "{{ index_build_command }}"

    - name: Build indexes
      shell: "/opt/couchbase/bin/cbq -u Admin -p redhat -s '{{ index_build_command }}'"
      ignore_errors: true
      register: build_index_output

    - name: Debug Build Output
      debug:
        msg: "{{ build_index_output }}"
