---
- name: Manage Couchbase indexes
  hosts: 54.225.130.193
  become: yes
  tasks:
    - name: Ensure jq is installed
      apt:
        name: jq
        state: present
        update_cache: yes

    - name: Read create index file
      ansible.builtin.slurp:
        src: /home/ubuntu/index_file.txt  # Update this path if necessary
      register: index_file_content

    - name: Decode the index creation SQL from the file
      set_fact:
        decoded_index_file_content: "{{ index_file_content['content'] | b64decode }}"

    - name: Debug decoded index file content
      debug:
        msg: "{{ decoded_index_file_content }}"

    - name: Extract index creation statements
      set_fact:
        index_creation_statements: "{{ decoded_index_file_content | regex_findall('CREATE INDEX `([^`]+)` ON `([^`]+)`\\.(`[^`]+`)\\.`([^`]+)`\\(([^)]+)\\) WITH \\{[^}]+\\};') }}"

    - name: Debug index creation statements
      debug:
        msg: "{{ index_creation_statements }}"

    - name: Create Indexes from File
      shell: |
        /opt/couchbase/bin/cbq -u azureuser -p redhat -s "{{ item }}"
      with_items: "{{ decoded_index_file_content | regex_findall('CREATE INDEX.*?;') }}"
      ignore_errors: true
      register: ddl_output

    - name: Build all indexes
      shell: |
        /opt/couchbase/bin/cbq -u azureuser -p redhat -s "
        BUILD INDEX ON `{{ item.1 }}`.`{{ item.2 }}`.`{{ item.3 }}` (`{{ item.4 }}`);
        "
      with_items: "{{ index_creation_statements }}"
      register: build_output
