---
- name: Manage Couchbase indexes
  hosts: all
  become: yes
  tasks:
   
    - name: Validate index file existence
      ansible.builtin.stat:
        path: /home/ubuntu/Couchbase_UPS/Clause_without_Clause.txt
      register: index_file_stat

    - name: Fail if index file is missing
      fail:
        msg: "Index file not found: /home/ubuntu/Couchbase_UPS/Clause_without_Clause.txt"
      when: not index_file_stat.stat.exists

    - name: Read and decode index file
      ansible.builtin.slurp:
        src: /home/ubuntu/Couchbase_UPS/Clause_without_Clause.txt
      register: index_file_content

    - name: Decode the index file content
      set_fact:
        decoded_index_file_content: "{{ index_file_content.content | b64decode }}"

    - name: Debug decoded index file content
      debug:
        msg: "{{ decoded_index_file_content }}"

    - name: Extract index creation SQL
      set_fact:
        index_creation_statements: "{{ decoded_index_file_content | regex_findall('CREATE INDEX.*?;') }}"

    - name: Filter out invalid index creation statements
      set_fact:
        valid_index_creation_statements: "{{ index_creation_statements | selectattr('regex_search', args=['WHERE'], case_sensitive=False) | selectattr('regex_search', args=['_default'], negate=True) | list }}"

    - name: Debug valid index creation statements
      debug:
        msg: "{{ valid_index_creation_statements }}"

    - name: Validate Couchbase CLI availability
      shell: "/opt/couchbase/bin/cbq --version"
      register: cbq_check
      changed_when: false

    - name: Fail if there are no valid index creation statements
      fail:
        msg: "No valid index creation statements found"
      when: valid_index_creation_statements | length == 0

    - name: Create indexes
      shell: "/opt/couchbase/bin/cbq -u Admin -p redhat -s '{{ item }}'"
      with_items: "{{ valid_index_creation_statements }}"
      ignore_errors: true
      register: ddl_output

    - name: Debug output of index creation
      debug:
        msg: "{{ ddl_output.results | map(attribute='stderr') | join('\n') }}"

    - name: Extract build index SQL
      set_fact:
        build_index_statements: "{{ decoded_index_file_content | regex_findall('BUILD INDEX.*?;') }}"

    - name: Debug build index statements
      debug:
        msg: "{{ build_index_statements }}"

    - name: Build indexes
      shell: "/opt/couchbase/bin/cbq -u Admin -p redhat -s '{{ item }}'"
      with_items: "{{ build_index_statements }}"
      ignore_errors: true
      register: build_output

    - name: Debug output of index building
      debug:
        msg: "{{ build_output.results | map(attribute='stderr') | join('\n') }}"
