---
- name: Couchbase Cluster Resource Monitoring
  hosts: all
  gather_facts: false
  vars:
    # Thresholds (changeable)
    index_memory_threshold_percent: 75
    cpu_threshold_percent: 75
    memory_threshold_percent: 75
    disk_threshold_percent: 75

    # Webhook URL for alerts
    alert_webhook_url: "https://webhook.site/135d7b7c-96b1-42fe-8b3a-ed57d510c1d3"

  tasks:

    #########################################
    # 1️⃣ Index Memory Usage
    #########################################
    - name: Calculate Index Memory Quota & Threshold
      set_fact:
        index_quota_bytes: "{{ (api_response.json.indexMemoryQuota | int * 1024 * 1024) }}"
        index_threshold_bytes: "{{ (index_quota_bytes * index_memory_threshold_percent / 100) | int }}"

    - name: Sum index memory used across nodes
      set_fact:
        index_memory_used: "{{ api_response.json.nodes | map(attribute='interestingStats') | map(attribute='index_data_size') | map('int') | sum }}"

    - name: Send Index Memory Alert if usage exceeds threshold
      uri:
        url: "{{ alert_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase Index Memory Alert on {{ inventory_hostname }}"
          body: >
            ALERT: Index memory usage is above threshold!
            Current Usage: {{ index_memory_used }} bytes
            Threshold ({{ index_memory_threshold_percent }}%): {{ index_threshold_bytes }} bytes
            Host: {{ inventory_hostname }}
            Status: ❌ Index memory limit exceeded.
      when: index_memory_used > index_threshold_bytes

    #########################################
    # 2️⃣ CPU Usage per Node
    #########################################
    - name: Send CPU Alert if usage exceeds threshold
      uri:
        url: "{{ alert_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase CPU Alert on {{ inventory_hostname }}"
          body: >
            ALERT: CPU usage is above threshold!
            Node: {{ item.hostname }}
            Current CPU: {{ item.systemStats.cpu_utilization_rate }}%
            Threshold: {{ cpu_threshold_percent }}%
            Status: ❌ High CPU usage detected.
      loop: "{{ api_response.json.nodes }}"
      loop_control:
        label: "{{ item.hostname }}"
      when: item.systemStats.cpu_utilization_rate | float > cpu_threshold_percent

    #########################################
    # 3️⃣ Memory Usage per Node
    #########################################
    - name: Send Memory Alert if usage exceeds threshold
      uri:
        url: "{{ alert_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase Memory Alert on {{ inventory_hostname }}"
          body: >
            ALERT: Memory usage is above threshold!
            Node: {{ item.hostname }}
            Current Memory Used: {{ item.interestingStats.mem_used }} bytes
            Threshold ({{ memory_threshold_percent }}%): {{ (item.systemStats.mem_total | int * memory_threshold_percent / 100) | int }} bytes
            Status: ❌ High memory usage detected.
      loop: "{{ api_response.json.nodes }}"
      loop_control:
        label: "{{ item.hostname }}"
      when: item.interestingStats.mem_used | int > (item.systemStats.mem_total | int * memory_threshold_percent / 100)

    #########################################
    # 4️⃣ Disk Usage
    #########################################
    - name: Calculate disk usage percent
      set_fact:
        disk_used_percent: "{{ (api_response.json.storageTotals.hdd.used | float / api_response.json.storageTotals.hdd.total | float) * 100 }}"

    - name: Send Disk Alert if usage exceeds threshold
      uri:
        url: "{{ alert_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase Disk Alert on {{ inventory_hostname }}"
          body: >
            ALERT: Disk usage is above threshold!
            Current Usage: {{ disk_used_percent | round(2) }} %
            Threshold: {{ disk_threshold_percent }} %
            Total: {{ api_response.json.storageTotals.hdd.total }} bytes
            Used: {{ api_response.json.storageTotals.hdd.used }} bytes
            Free: {{ api_response.json.storageTotals.hdd.free }} bytes
            Status: ❌ High disk usage detected.
      when: disk_used_percent > disk_threshold_percent

    #########################################
    # 5️⃣ Summary Table
    #########################################
    - name: Generate Summary Table
      set_fact:
        summary_table: |
          Couchbase Resource Summary - {{ inventory_hostname }}

          Index Memory: {{ index_memory_used }} bytes / {{ index_quota_bytes }} bytes (Threshold {{ index_memory_threshold_percent }}%)
          Disk Usage: {{ api_response.json.storageTotals.hdd.used }} bytes / {{ api_response.json.storageTotals.hdd.total }} bytes ({{ disk_used_percent | round(2) }}%, Threshold {{ disk_threshold_percent }}%)

          CPU Usage per Node:
          {% for node in api_response.json.nodes %}
            - {{ node.hostname }}: {{ node.systemStats.cpu_utilization_rate }}% (Threshold {{ cpu_threshold_percent }}%)
          {% endfor %}

          Memory Usage per Node:
          {% for node in api_response.json.nodes %}
            - {{ node.hostname }}: {{ node.interestingStats.mem_used }} bytes / {{ node.systemStats.mem_total }} bytes (Threshold {{ memory_threshold_percent }}%)
          {% endfor %}

    - name: Display Summary Table
      debug:
        msg: "{{ summary_table }}"
