---
- name: Automate Couchbase Checks
  hosts: all
  become: true
  tasks:

    - name: Ensure /home/ubuntu directory exists
      file:
        path: /home/ubuntu
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Move couch_check_all.sh to /opt/couchbase/bin/
      command: mv couch_check_all.sh /opt/couchbase/bin/
      args:
        chdir: /home/ubuntu

    - name: Move couch_check to /opt/couchbase/bin/
      command: mv couch_check /opt/couchbase/bin/
      args:
        chdir: /home/ubuntu

    - name: Make couch_check executable
      file:
        path: /opt/couchbase/bin/couch_check
        mode: '0755'

    - name: Make couch_check_all.sh executable
      file:
        path: /opt/couchbase/bin/couch_check_all.sh
        mode: '0755'

    

