---
- name: Check Couchbase Server Health via AWX
  hosts: all
  gather_facts: no
  vars:
    cb_admin: []
    cb_pass: []
    couchbase_ports: [8091, 8092, 8093, 8094, 11210, 11207, 11209, 18091, 18092, 18093, 4369, 21100]

  tasks:
    - name: ✅ Check if Couchbase service is running
      ansible.builtin.systemd:
        name: couchbase-server
        state: started
      register: couchbase_status
      failed_when: couchbase_status.status.ActiveState != "active"

    - name: 📋 Retrieve Couchbase cluster node list
      shell: "/opt/couchbase/bin/couchbase-cli server-list -c 127.0.0.1 -u '{{ cb_admin }}' -p '{{ cb_pass }}'"
      register: cluster_status
      changed_when: false
      failed_when: false 

    - name: 🚨 Check if cluster node list command failed
      fail:
        msg: "❌ Failed to retrieve Couchbase cluster node list. Check if the cluster is running and credentials are correct."
      when: cluster_status.rc != 0

    - name: ✅ Debug cluster output (if needed)
      debug:
        msg: "{{ cluster_status.stdout }}"
      when: cluster_status.rc == 0  

    - name: ❓ Check if cluster is healthy
      ansible.builtin.fail:
        msg: "❌ Couchbase cluster is NOT healthy.\nOutput:\n{{ cluster_status.stdout }}"
      when: "'healthy active' not in cluster_status.stdout"

    - name: ✅ Display Couchbase nodes and status
      shell: "/opt/couchbase/bin/couchbase-cli server-list -c 127.0.0.1 -u '{{ cb_admin }}' -p '{{ cb_pass }}' | awk '{print \"Node: \" $2 \" | Status: \" $3 \" \" $4}'"
      register: nodes_output
      changed_when: false

    - name: Show parsed Couchbase node info
      ansible.builtin.debug:
        var: nodes_output.stdout_lines
