---
- name: Couchbase Resource Monitoring
  hosts: all
  gather_facts: false

  vars:
    # Thresholds (adjustable)
    index_memory_threshold_percent: 75
    cpu_threshold_percent: 75
    memory_threshold_percent: 75
    disk_threshold_percent: 75
    alert_webhook_url: "https://webhook.site/135d7b7c-96b1-42fe-8b3a-ed57d510c1d3"

  tasks:

    ###########################
    # Fetch Couchbase cluster info
    ###########################
    - name: Get Couchbase cluster info
      uri:
        url: "http://127.0.0.1:8091/pools/default"
        method: GET
        user: "Admin"
        password: "redhat"
        force_basic_auth: yes
        return_content: yes
      register: cluster_info

    - name: Parse cluster info JSON
      set_fact:
        cluster_json: "{{ cluster_info.json }}"

    - name: Get node/self info
      uri:
        url: "http://127.0.0.1:8091/nodes/self"
        method: GET
        user: "Admin"
        password: "redhat"
        force_basic_auth: yes
        return_content: yes
      register: node_info

    - name: Parse node JSON
      set_fact:
        node_json: "{{ node_info.json }}"

    ###########################
    # Index Memory Check
    ###########################
    - name: Calculate Index Memory in bytes
      set_fact:
        index_quota_bytes: "{{ (cluster_json.indexMemoryQuota | default(0) | int) * 1024 * 1024 }}"

    - name: Calculate Index Memory Threshold (75% by default)
      set_fact:
        index_threshold_bytes: "{{ (index_quota_bytes * (index_memory_threshold_percent | float) / 100) | round(0) | int }}"

    - name: Get current index memory used
      set_fact:
        index_memory_used: "{{ node_json.interestingStats.index_data_size | default(0) | int }}"

    - name: Send alert if index memory exceeds threshold
      uri:
        url: "{{ alert_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase Index Memory Alert on {{ inventory_hostname }}"
          body: >
            ALERT: Index Memory usage is above threshold!
            Current Memory: {{ (index_memory_used | float / 1024 / 1024) | round(2) }} MiB
            Threshold ({{ index_memory_threshold_percent }}% of quota): {{ (index_threshold_bytes | float / 1024 / 1024) | round(2) }} MiB
      when: index_memory_used | int > index_threshold_bytes | int

    ###########################
    # CPU Usage Check
    ###########################
    - name: Get CPU usage safely
      set_fact:
        cpu_used: "{{ node_json.systemStats.cpu_utilization_rate | default(0) | float }}"

    - name: Send alert if CPU exceeds threshold
      uri:
        url: "{{ alert_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase CPU Alert on {{ inventory_hostname }}"
          body: >
            ALERT: CPU usage is above threshold!
            Current CPU: {{ cpu_used }}%
            Threshold: {{ cpu_threshold_percent }}%
      when: cpu_used > cpu_threshold_percent

    ###########################
    # Memory Usage Check
    ###########################
    - name: Get Memory usage safely
      set_fact:
        mem_total: "{{ node_json.systemStats.mem_total | default(0) | int }}"
        mem_free:  "{{ node_json.systemStats.mem_free  | default(0) | int }}"
        mem_used:  "{{ mem_total - mem_free }}"
        mem_threshold_bytes: "{{ (mem_total * (memory_threshold_percent | float) / 100) | int }}"

    - name: Send alert if memory exceeds threshold
      uri:
        url: "{{ alert_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase Memory Alert on {{ inventory_hostname }}"
          body: >
            ALERT: Memory usage is above threshold!
            Current Memory: {{ (mem_used | float / 1024 / 1024) | round(2) }} MiB
            Threshold: {{ (mem_threshold_bytes | float / 1024 / 1024) | round(2) }} MiB
      when: mem_used > mem_threshold_bytes

    ###########################
    # Disk Usage Check
    ###########################
    - name: Get HDD totals and usage safely
      set_fact:
        disk_total: "{{ node_json.storageTotals.hdd.total | default(0) | int }}"
        disk_used:  "{{ node_json.storageTotals.hdd.used  | default(0) | int }}"
        disk_free:  "{{ node_json.storageTotals.hdd.free  | default(0) | int }}"
        disk_used_percent: "{{ ((disk_used | float / disk_total | float) * 100) | round(2) }}"

    - name: Send alert if disk exceeds threshold
      uri:
        url: "{{ alert_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase Disk Alert on {{ inventory_hostname }}"
          body: >
            ALERT: Disk usage is above threshold!
            Current Usage: {{ disk_used_percent }} %
            Threshold: {{ disk_threshold_percent }} %
            Total: {{ (disk_total | float / 1024 / 1024 / 1024) | round(2) }} GiB
            Used:  {{ (disk_used | float / 1024 / 1024 / 1024) | round(2) }} GiB
            Free:  {{ (disk_free | float / 1024 / 1024 / 1024) | round(2) }} GiB
      when: disk_used_percent > disk_threshold_percent

    ###########################
    # Summary Table
    ###########################
    - name: Show summary of all metrics vs thresholds
      debug:
        msg: |
          ===== Couchbase Resource Summary on {{ inventory_hostname }} =====
          Index Memory: {{ (index_memory_used | float / 1024 / 1024) | round(2) }} MiB / Threshold: {{ (index_threshold_bytes | float / 1024 / 1024) | round(2) }} MiB
          CPU Usage: {{ cpu_used }} % / Threshold: {{ cpu_threshold_percent }} %
          Memory Usage: {{ (mem_used | float / 1024 / 1024) | round(2) }} MiB / Threshold: {{ (mem_threshold_bytes | float / 1024 / 1024) | round(2) }} MiB
          Disk Usage: {{ disk_used_percent }} % / Threshold: {{ disk_threshold_percent }} %
          Total Disk: {{ (disk_total | float / 1024 / 1024 / 1024) | round(2) }} GiB, Used: {{ (disk_used | float / 1024 / 1024 / 1024) | round(2) }} GiB, Free: {{ (disk_free | float / 1024 / 1024 / 1024) | round(2) }} GiB
