---
- name: Run Couchbase Check Script
  hosts: all
  become: yes
  tasks:

    - name: Make couch_check76 executable
      ansible.builtin.file:
        path: /opt/couchbase/bin/couch_check76
        mode: '0755'

    - name: Make couch_check_all76.sh executable
      ansible.builtin.file:
        path: /opt/couchbase/bin/couch_check_all76.sh
        mode: '0755'

    - name: Run couch_check_all76.sh with environment variable and arguments
      ansible.builtin.shell: >
        /opt/couchbase/bin/couch_check_all76.sh /opt/couchbase/var/lib/couchbase/data/travel-sample/*.couch > /home/ubuntu/output.txt 
      environment:
        COUCH_CHECK_PATH: /opt/couchbase/bin
