---
- name: Couchbase Resource Monitoring
  hosts: all
  gather_facts: false
  vars:
    # Thresholds (users can change these)
    index_memory_threshold_percent: 75
    cpu_threshold_percent: 75
    memory_threshold_percent: 75
    disk_threshold_percent: 75

    # Webhook URL for notifications
    webhook_url: "https://webhook.site/135d7b7c-96b1-42fe-8b3a-ed57d510c1d3"

  tasks:
    - name: Get Couchbase cluster info (mocked with /pools/default JSON)
      uri:
        url: "http://127.0.0.1:8091/pools/default"
        method: GET
        return_content: yes
        user: "Admin"
        password: "redhat"
        force_basic_auth: yes
      register: cluster_info

    - name: Get Couchbase node info (mocked with /nodes/self JSON)
      uri:
        url: "http://127.0.0.1:8091/nodes/self"
        method: GET
        return_content: yes
        user: "Admin"
        password: "redhat"
        force_basic_auth: yes
      register: node_info

    - name: Parse JSON responses
      set_fact:
        cluster_json: "{{ cluster_info.json }}"
        node_json: "{{ node_info.json }}"

    ###########################
    # INDEX MEMORY USAGE CHECK
    ###########################
    - name: Calculate Index Memory Quota in bytes
      set_fact:
        index_quota_bytes: "{{ cluster_json.indexMemoryQuota | int * 1024 * 1024 }}"

    - name: Calculate Index Memory Threshold (75% by default)
      set_fact:
        index_quota_threshold: "{{ (index_quota_bytes * index_memory_threshold_percent / 100) | int }}"

    - name: Get current index memory used
      set_fact:
        index_mem_used: "{{ node_json.interestingStats.index_data_size | int }}"

    - name: Send alert if Index Memory exceeds threshold
      uri:
        url: "{{ webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase Index Memory Alert on {{ inventory_hostname }}"
          body: >
            ALERT: Index Memory usage exceeded threshold!
            Current: {{ (index_mem_used / 1024 / 1024) | round(2) }} MiB
            Threshold: {{ (index_quota_threshold / 1024 / 1024) | round(2) }} MiB
      when: index_mem_used > index_quota_threshold

    ###########################
    # CPU USAGE CHECK
    ###########################
    - name: Get current CPU usage
      set_fact:
        cpu_used: "{{ node_json.systemStats.cpu_utilization_rate | float }}"

    - name: Send alert if CPU exceeds threshold
      uri:
        url: "{{ webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase CPU Alert on {{ inventory_hostname }}"
          body: >
            ALERT: CPU usage exceeded threshold!
            Current: {{ cpu_used }} %
            Threshold: {{ cpu_threshold_percent }} %
      when: cpu_used > cpu_threshold_percent

    ###########################
    # MEMORY USAGE CHECK
    ###########################
    - name: Calculate Memory Threshold in bytes
      set_fact:
        memory_threshold_bytes: "{{ node_json.systemStats.mem_total | int * memory_threshold_percent / 100 }}"

    - name: Get current memory used
      set_fact:
        memory_used: "{{ node_json.interestingStats.mem_used | int }}"

    - name: Send alert if Memory exceeds threshold
      uri:
        url: "{{ webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase Memory Alert on {{ inventory_hostname }}"
          body: >
            ALERT: Memory usage exceeded threshold!
            Current: {{ (memory_used / 1024 / 1024) | round(2) }} MiB
            Threshold: {{ (memory_threshold_bytes / 1024 / 1024) | round(2) }} MiB
      when: memory_used > memory_threshold_bytes

    ###########################
    # DISK USAGE CHECK
    ###########################
    - name: Get HDD totals and usage
      set_fact:
        disk_total: "{{ node_json.storageTotals.hdd.total | int }}"
        disk_used: "{{ node_json.storageTotals.hdd.used | int }}"
        disk_free: "{{ node_json.storageTotals.hdd.free | int }}"
        disk_used_percent: "{{ ((disk_used / disk_total) * 100) | round(2) }}"

    - name: Send alert if Disk exceeds threshold
      uri:
        url: "{{ webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase Disk Alert on {{ inventory_hostname }}"
          body: >
            ALERT: Disk usage exceeded threshold!
            Current: {{ disk_used_percent }} %
            Threshold: {{ disk_threshold_percent }} %
            Total: {{ (disk_total / 1024 / 1024 / 1024) | round(2) }} GiB
            Used: {{ (disk_used / 1024 / 1024 / 1024) | round(2) }} GiB
            Free: {{ (disk_free / 1024 / 1024 / 1024) | round(2) }} GiB
      when: disk_used_percent > disk_threshold_percent

    ###########################
    # SUMMARY TABLE
    ###########################
    - name: Show summary of all metrics vs thresholds
      debug:
        msg: |
          Couchbase Monitoring Summary ({{ inventory_hostname }}):
          ----------------------------------------------------
          Index Memory: {{ (index_mem_used / 1024 / 1024) | round(2) }} MiB / {{ (index_quota_threshold / 1024 / 1024) | round(2) }} MiB ({{ index_memory_threshold_percent }}% threshold)
          CPU Usage: {{ cpu_used }} % / {{ cpu_threshold_percent }} %
          Memory Usage: {{ (memory_used / 1024 / 1024) | round(2) }} MiB / {{ (memory_threshold_bytes / 1024 / 1024) | round(2) }} MiB ({{ memory_threshold_percent }}% threshold)
          Disk Usage: {{ disk_used_percent }} % / {{ disk_threshold_percent }} %
