---
- name: Run Couchbase check scripts
  hosts: all
  become: true
  tasks:
    - name: Create output directory
      file:
        path: /home/ubuntu
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Move couch_check to Couchbase bin directory
      copy:
        src: couch_check
        dest: /opt/couchbase/bin/couch_check
        mode: '0755'
        owner: couchbase
        group: couchbase

    - name: Move couch_check_all.sh to Couchbase bin directory
      copy:
        src: couch_check_all.sh
        dest: /opt/couchbase/bin/couch_check_all.sh
        mode: '0755'
        owner: couchbase
        group: couchbase

    - name: Run couch_check_all.sh on .couch files
      shell: |
        export COUCH_CHECK_PATH=/opt/couchbase/bin
        cd /opt/couchbase/var/lib/couchbase/data/travel-sample
        /opt/couchbase/bin/couch_check_all.sh *.couch > /home/ubuntu/output_couch_check_all.txt
      args:
        executable: /bin/bash
      become_user: couchbase
