---
- name: Couchbase Resource Monitor
  hosts: all
  gather_facts: false
  vars:
    # Thresholds
    index_memory_threshold_percent: 5
    cpu_threshold_percent: 5
    memory_threshold_percent: 5
    disk_threshold_percent: 5
    alert_webhook_url: "https://webhook.site/92b2481a-73e1-4d6b-b6b9-54f004620b03"

  tasks:

    ###########################
    # FETCH COUCHBASE DATA
    ###########################
    - name: Get Couchbase cluster info
      uri:
        url: "http://127.0.0.1:8091/pools/default"
        method: GET
        return_content: yes
        user: "Admin"
        password: "redhat"
        force_basic_auth: yes
      register: cluster_json

    - name: Get self node info
      uri:
        url: "http://127.0.0.1:8091/nodes/self"
        method: GET
        return_content: yes
        user: "Admin"
        password: "redhat"
        force_basic_auth: yes
      register: node_json_response

    - name: Parse self node JSON
      set_fact:
        node_json: "{{ node_json_response.json }}"

    ###########################
    # INDEX MEMORY CHECK
    ###########################
    - name: Get Index Memory Quota in bytes
      set_fact:
        index_quota_bytes: "{{ (cluster_json.json.indexMemoryQuota | default(0) | int * 1024 * 1024) }}"

    - name: Calculate Index Memory Threshold
      set_fact:
        index_threshold_bytes: "{{ (index_quota_bytes | float * (index_memory_threshold_percent | float) / 100) | round(0) | int }}"

    - name: Get actual Index Memory Used in bytes
      set_fact:
        index_used_bytes: "{{ node_json.interestingStats.index_disk_size | default(0) | int }}"

    - name: Alert if Index Memory exceeds threshold
      uri:
        url: "{{ alert_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase Index Memory Alert on {{ inventory_hostname }}"
          body: >
            ALERT: Index memory usage above threshold!
            Used: {{ index_used_bytes | int }} bytes ({{ (index_used_bytes | int / 1024 / 1024) | round(2) }} MiB)
            Threshold: {{ (index_threshold_bytes | int / 1024 / 1024) | round(2) }} MiB
      when: index_used_bytes | int > index_threshold_bytes | int

    ###########################
    # CPU USAGE CHECK
    ###########################
    - name: Get CPU usage safely
      set_fact:
        cpu_used: "{{ (node_json.systemStats.cpu_utilization_rate | float) | round(2) }}"

    - name: Debug CPU stats
      debug:
        msg:
          cpu_used: "{{ cpu_used }}"
          threshold: "{{ cpu_threshold_percent }}"
          condition_result: "{{ cpu_used | float > cpu_threshold_percent | float }}"

    - name: Alert if CPU exceeds threshold
      uri:
        url: "{{ alert_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase CPU Alert on {{ inventory_hostname }}"
          body: >
            ALERT: CPU usage above threshold!
            Current CPU: {{ cpu_used }}%
            Threshold: {{ cpu_threshold_percent }}%
      when: cpu_used | float > cpu_threshold_percent | float

    ###########################
    # MEMORY USAGE CHECK
    ###########################
    - name: Get Memory total safely
      set_fact:
        memory_total: "{{ node_json.systemStats.mem_total | default(0) | float }}"

    - name: Get Memory free safely
      set_fact:
        memory_free: "{{ node_json.systemStats.mem_free | default(0) | float }}"

    - name: Calculate Memory used and threshold
      set_fact:
        memory_used: "{{ (memory_total | float) - (memory_free | float) }}"
        memory_threshold_bytes: "{{ (memory_total | float) * (memory_threshold_percent | float) / 100 }}"

    - name: Debug Memory stats
      debug:
        msg:
          memory_total: "{{ (memory_total | float / 1024 / 1024) | round(2) }} MiB"
          memory_free: "{{ (memory_free | float / 1024 / 1024) | round(2) }} MiB"
          memory_used: "{{ (memory_used | float / 1024 / 1024) | round(2) }} MiB"
          threshold: "{{ (memory_threshold_bytes | float / 1024 / 1024) | round(2) }} MiB"
          condition_result: "{{ (memory_used | float) > (memory_threshold_bytes | float) }}"

    - name: Alert if Memory exceeds threshold
      uri:
        url: "{{ alert_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase Memory Alert on {{ inventory_hostname }}"
          body: >
            ALERT: Memory usage above threshold!
            Used: {{ (memory_used | float / 1024 / 1024) | round(2) }} MiB
            Threshold: {{ (memory_threshold_bytes | float / 1024 / 1024) | round(2) }} MiB
      when: (memory_used | float) > (memory_threshold_bytes | float)

    ###########################
    # DISK USAGE CHECK
    ###########################
    - name: Ensure node_json and HDD data exists
      set_fact:
        hdd_info: "{{ node_json.storageTotals.hdd | default({'total': 0, 'used': 0}) }}"
      when: node_json is defined

    - name: Set disk facts safely
      set_fact:
        disk_total: "{{ hdd_info.total | float }}"
        disk_used: "{{ hdd_info.used | float }}"
        disk_used_percent: >-
          {% if (hdd_info.total | float) > 0 %}
            {{ ((hdd_info.used | float) / (hdd_info.total | float) * 100) | round(2) }}
          {% else %}
            0
          {% endif %}
      when: hdd_info is defined

    - name: Debug Disk stats
      debug:
        msg:
          disk_total: "{{ (disk_total | float / 1024 / 1024 / 1024) | round(2) }} GiB"
          disk_used: "{{ (disk_used | float / 1024 / 1024 / 1024) | round(2) }} GiB"
          disk_used_percent: "{{ disk_used_percent | float }}"
          threshold: "{{ disk_threshold_percent | float }}"
          condition_result: "{{ (disk_used_percent | float) > (disk_threshold_percent | float) }}"
      when: disk_total is defined and disk_used is defined

    - name: Alert if Disk exceeds threshold
      uri:
        url: "{{ alert_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          subject: "🚨 Couchbase Disk Alert on {{ inventory_hostname }}"
          body: >
            ALERT: Disk usage above threshold!
            Usage: {{ disk_used_percent | float }}%
            Threshold: {{ disk_threshold_percent | float }}%
            Total: {{ (disk_total | float / 1024 / 1024 / 1024) | round(2) }} GiB
            Used: {{ (disk_used | float / 1024 / 1024 / 1024) | round(2) }} GiB
      when: disk_used_percent is defined and (disk_used_percent | float) > (disk_threshold_percent | float)

    ###########################
    # SUMMARY TABLE
    ###########################
    
    - name: Display Couchbase Resource Summary as key-value
      debug:
        msg:
          Index_Memory: "{{ (index_used_bytes | int / 1024 / 1024) | round(2) }} MiB / {{ (index_threshold_bytes | int / 1024 / 1024) | round(2) }} MiB"
          CPU_Usage: "{{ cpu_used | float | round(2) }} % / {{ cpu_threshold_percent | float | round(2) }} %"
          Memory_Usage: "{{ (memory_used | int / 1024 / 1024) | round(2) }} MiB / {{ (memory_threshold_bytes | int / 1024 / 1024) | round(2) }} MiB"
          Disk_Usage: "{{ disk_used_percent | float | round(2) }} % / {{ disk_threshold_percent | float | round(2) }} %"  

    - name: Fail if any Couchbase resource threshold exceeded
      fail:
        msg: |
          {% if disk_used_percent | float > disk_threshold_percent | float %}
          Disk usage above threshold! Usage: {{ disk_used_percent | float | round(2) }}%
          Threshold: {{ disk_threshold_percent | float }}%
          Total: {{ (disk_total | float / 1024 / 1024 / 1024) | round(2) }} GiB
          Used: {{ (disk_used | float / 1024 / 1024 / 1024) | round(2) }} GiB

          {% endif %}
          {% if memory_used | float > memory_threshold_bytes | float %}
          Memory usage above threshold! Used: {{ (memory_used | float / 1024 / 1024) | round(2) }} MiB
          Threshold: {{ (memory_threshold_bytes | float / 1024 / 1024) | round(2) }} MiB

          {% endif %}
          {% if index_used_bytes | int > index_threshold_bytes | int %}
          Index memory usage above threshold! Used: {{ index_used_bytes | int }} bytes
          ({{ (index_used_bytes | int / 1024 / 1024) | round(2) }} MiB)
          Threshold: {{ (index_threshold_bytes | int / 1024 / 1024) | round(2) }} MiB

          {% endif %}
          {% if cpu_used | float > cpu_threshold_percent | float %}
          CPU usage above threshold! Current CPU: {{ cpu_used | float | round(2) }}%
          Threshold: {{ cpu_threshold_percent | float }}%

          {% endif %}
      when: >
        index_used_bytes | int > index_threshold_bytes | int
        or cpu_used | float > cpu_threshold_percent | float
        or memory_used | float > memory_threshold_bytes | float
        or disk_used_percent | float > disk_threshold_percent | float




