---
- name: Run Couchbase couch_check commands
  hosts: all
  become: yes
  tasks:
    - name: Create output file placeholder
      shell: mkdir -p "{{ output_dir | default('/home/ubuntu') }}" && touch output_couch_check_all.txt
      args:
        chdir: /home/ubuntu

    # - name: Uncompress couch_check.gz
    #   shell: |
    #     cd /home/ubuntu
    #     gunzip -f couch_check.gz

    - name: Make couch_check and couch_check_all.sh executable
      file:
        path: "{{ item }}"
        mode: '0755'
      loop:
        - /opt/couchbase/bin/couch_check
        - /opt/couchbase/bin/couch_check_all.sh

    - name: Run couch_check_all.sh on travel-sample .couch files
      shell: |
        export COUCH_CHECK_PATH=/opt/couchbase/bin
        cd /opt/couchbase/var/lib/couchbase/data/travel-sample
        /opt/couchbase/bin/couch_check_all.sh *.couch > /home/ubuntu/output_couch_check_all.txt
