---
- name: Get Couchbase indexes and save to file
  hosts: all
  become: true
  vars:
    couchbase_url: "http://localhost:8093"
    couchbase_user: ""
    couchbase_pass: ""
  tasks:
    - name: Run cbq to get index list
      shell: >
        /opt/couchbase/bin/cbq
        -u {{ couchbase_user }}
        -p {{ couchbase_pass }}
        -e {{ couchbase_url }}
        -script "SELECT * FROM system:indexes;" > /tmp/index_list.txt
      args:
        executable: /bin/bash

    - name: Read contents of index_list.txt
      command: cat /home/ubuntu/index_list.txt
      register: index_output

    - name: Print index content to output
      debug:
        msg: "{{ index_output.stdout }}"
    
