---
- name: Get Couchbase indexes and save to file
  hosts: all
  become: true
  tasks:
    - name: Run cbq to get index list
      shell: >
        /opt/couchbase/bin/cbq -u Admin -p redhat -e http://localhost:8093
        -script "SELECT * FROM system:indexes;" > /tmp/index_list.txt
      args:
        executable: /bin/bash
