---
- name: Copy and run monitor.sh on the worker node
  hosts: all
  become: yes
  vars:
  

  tasks:
    - name: Copy monitor.sh to /home/ubuntu
      copy:
        src: "{{ playbook_dir }}/monitor.sh"
        dest: /home/ubuntu/monitor.sh
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Run monitor.sh script once
      shell: /home/ubuntu/monitor.sh
      args:
        chdir: /home/ubuntu
      become_user: ubuntu

    
