- name: Monitor the cluster and node
  hosts: all
  gather_facts: no

  tasks:
    - name: Copy the disk error check script to remote host
      copy:
        src: /home/ubuntu/monitor_cluster.sh  # Absolute path on Ansible controller
        dest: /home/ubuntu/monitor_cluster.sh  # Destination on remote host
        mode: '0755'

    - name: Run the disk error check script on remote host
      shell: /home/ubuntu/monitor_cluster.sh
