---
- name: Deploy monitor script to worker node
  hosts: all
  become: true
  tasks:
    - name: Copy monitor.sh to /home/ubuntu/
      copy:
        src: monitor.sh         # relative to project root
        dest: /home/ubuntu/monitor.sh
        owner: ubuntu
        group: ubuntu
        mode: '0755'
