- name: Transfer script to worker node
  hosts: worker_nodes
  become: true
  tasks:
    - name: Copy monitor.sh to /home/ubuntu/
      copy:
        src: /tmp/monitor.sh
        dest: /home/ubuntu/monitor.sh
        owner: ubuntu
        group: ubuntu
        mode: '0755'
