---
- name: Deploy and run monitor_cluster.sh on worker node
  hosts: all  # Make sure this group or host is defined in your inventory
  become: true   # Elevate privileges to access user home directory
  tasks:

    - name: Copy monitor_cluster.sh to /home/ubuntu
      copy:
        src: /home/ubuntu/monitor_cluster.sh
        dest: /home/ubuntu/monitor_cluster.sh
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Run monitor_cluster.sh as ubuntu user
      become: true
      become_user: ubuntu
      command: /home/ubuntu/monitor_cluster.sh
