---
- name: Copy script from AWX container and send to worker node
  hosts: localhost
  tasks:
    - name: Copy script from container to host
      command: docker cp awx_task:/path/in/container/myscript.sh /tmp/myscript.sh
      become: true

- name: Transfer script to worker node
  hosts: worker_nodes
  become: true
  tasks:
    - name: Copy script to /home/ubuntu/
      copy:
        src: /tmp/myscript.sh
        dest: /home/ubuntu/myscript.sh
        owner: ubuntu
        group: ubuntu
        mode: '0755'
