---
- name: Deploy and run monitor_cluster.sh on worker node
  hosts: all
  become: true

  tasks:

    - name: Copy monitor_cluster.sh from control node to worker node
      copy:
        src: /home/ubuntu/monitor_cluster.sh
        dest: /home/ubuntu/monitor_cluster.sh
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Run monitor_cluster.sh as ubuntu user
      become: true
      become_user: ubuntu
      command: /home/ubuntu/monitor_cluster.sh
