---
- name: Copy monitor.sh to worker node home directory
  hosts: all
  become: yes
  tasks:
    - name: Copy monitor.sh to /home/ubuntu on the target node
      copy:
        src: "{{ playbook_dir }}/monitor.sh"
        dest: /home/ubuntu/monitor.sh
        mode: '0755'
        owner: ubuntu
        group: ubuntu
