---
- name: Copy monitor_cluster.sh to remote host
  hosts: all
  become: true
  tasks:
    - name: Ensure destination directory exists
      file:
        path: /home/ubuntu 
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy monitor_cluster.sh to remote host
      copy:
        src: /home/ubuntu/monitor_cluster.sh
        dest: /home/ubuntu/monitor_cluster.sh
        owner: ubuntu
        group: ubuntu
        mode: '0755'
