- name: Monitor the cluster and node
  hosts: all
  gather_facts: no

  tasks:
    - name: Copy the disk error check script to remote host
      copy:
        src: "{{ lookup('env','HOME') }}/monitor_cluster.sh"
        dest: /home/ubuntu/monitor_cluster.sh
        mode: '0755'

    - name: Run the disk error check script on remote host
      shell: /home/ubuntu/monitor_cluster.sh
