---
- name: Copy monitor_cluster.sh to worker node
  hosts: all
  tasks:
    - name: Copy monitor_cluster.sh file
      copy:
        src: /home/ubuntu/monitor_cluster.sh
        dest: /home/ubuntu/monitor_cluster.sh
      become: yes  # Use this if you need elevated privileges
