---
- name: Step 1 - Copy script from awx_task container to AWX host
  hosts: localhost
  become: true
  tasks:
    - name: Create temporary directory to store script
      file:
        path: /tmp/awx_scripts
        state: directory
        mode: '0755'

    - name: Copy script from awx_task container to host
      command: docker cp awx_task:/monitor.sh /tmp/awx_scripts/monitor.sh

- name: Step 2 - Transfer script to worker node
  hosts: worker_nodes
  become: true
  tasks:
    - name: Copy monitor.sh to /home/ubuntu/
      copy:
        src: /tmp/awx_scripts/monitor.sh
        dest: /home/ubuntu/monitor.sh
        owner: ubuntu
        group: ubuntu
        mode: '0755'
