- name: Monitor the cluster and node
  hosts: all
  gather_facts: no

  tasks:
    - name: Copy monitor_check check script to remote host
      copy:
        src: /home/ubuntu/monitor_cluster.sh
        dest: /home/ubuntu/
        mode: '0755'

    - name: Run the script 
      shell: /home/ubuntu/monitor_cluster.sh
