---
- name: Copy monitor_cluster.sh to worker node
  hosts: all
  tasks:
    - name: Copy monitor_cluster.sh file
      copy:
        src: /home/ubuntu/monitor_cluster.sh  # Adjust this path to where the file is accessible in the Docker container
        dest: /home/ubuntu
      become: yes  # Use this if you need elevated privileges
