---
- hosts: all
  gather_facts: no
  tasks:

    - name: Install Python 3 and pip
      raw: sudo apt-get update && sudo apt-get install -y python3 python3-pip

    - name: Ping EC2
      ansible.builtin.ping:
