---
- name: Test connectivity to hosts
  hosts: all        # Or you can specify a group from your inventory (e.g., 'webservers')
  gather_facts: no  # Not needed for a simple ping

  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:
