---
- name: Bootstrap Ubuntu EC2 instance and verify with ping
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Install Python3 and pip3 using raw
      raw: apt-get update && apt-get install -y python3 python3-pip

    - name: Install six using raw (so Ansible modules can run)
      raw: pip3 install six setuptools wheel

    - name: Gather facts now that Python and six are installed
      setup:

    - name: Verify connectivity with Ansible ping
      ansible.builtin.ping:
