---
- name: Check Couchbase Ports on Remote Server
  hosts: all
  gather_facts: false
  become: true

  vars:
    couchbase_ports:
      - 8091
      - 8092
      - 8093
      - 8094
      - 11210
      - 11207
      - 11209
      - 18091
      - 18092
      - 18093
      - 4369
      - 21100

  tasks:

    - name: Ensure lsof is installed
      package:
        name: lsof
        state: present

    - name: Check each Couchbase port
      shell: |
        SERVICE=$(lsof -i :{{ item }} | awk 'NR>1 {print $1}' | uniq | paste -sd "," -)
        if [ -n "$SERVICE" ]; then
          echo "CLOSED - Services: [$SERVICE]"
        else
          echo "OPEN"
        fi
      register: port_status
      loop: "{{ couchbase_ports }}"
      changed_when: false

    - name: Show summarized port check output
      debug:
        msg: "Port {{ item.item }}: {{ item.stdout }}"
      loop: "{{ port_status.results }}"    

    - 
