---
- name: Check Couchbase Ports on Remote Server
  hosts: all
  gather_facts: false
  become: true

  vars:
    couchbase_ports:
      - 8091
      - 8092
      - 8093
      - 8094
      - 11210
      - 11207
      - 11209
      - 18091
      - 18092
      - 18093
      - 4369
      - 21100

  tasks:

    - name: Ensure lsof is installed
      package:
        name: lsof
        state: present

    - name: Check each Couchbase port
      shell: |
        SERVICE=$(lsof -i :{{ item }} | awk 'NR>1 {print $1}' | uniq | paste -sd "," -)
        if [ -n "$SERVICE" ]; then
          echo "CLOSED - Services: [$SERVICE]"
        else
          echo "OPEN"
        fi
      register: port_status
      loop: "{{ couchbase_ports }}"
      changed_when: false

    - name: Summarize port statuses
      set_fact:
        port_summary: >-
          {{ port_summary | default([]) + [item.item ~ ':' ~ item.stdout] }}
      loop: "{{ port_status.results }}"

    - name: Display summarized result
      debug:
        msg: "{{ port_summary | join(', ') }}"




    - name: Summarize port statuses
      set_fact:
        port_summary: >-
          {{ port_summary | default([]) + [item.item ~ ':' ~ item.stdout] }}
      loop: "{{ port_status.results }}"

    - name: Display port summary in readable format
      debug:
        msg: |
          Port Status Summary:
          {% for entry in port_summary %}
          - {{ entry }}
          {% endfor %}    



    - name: Prepare structured port data
      set_fact:
        structured_ports: >-
          {{
            structured_ports | default([]) + [{
              'port': entry.split(':')[0],
              'status': (entry.split(':')[1]).split('-')[0] | trim,
              'services': (
                entry.find('Services:') != -1
                and entry.split('Services:')[1] | trim(' []')
                or ''
              )
            }]
          }}
      loop: "{{ port_summary }}"
      loop_control:
        loop_var: entry

    - name: Display port summary in clean format
      debug:
        msg: |
          Port Status Summary:
          {% for item in structured_ports %}
          - Port {{ item.port }}: {{ item.status }}
            {% if item.services %}
            Services: {{ item.services }}
            {% endif %}
          {% endfor %} 
