---
- name: Check Couchbase Ports on Remote Server
  hosts: all
  gather_facts: false
  become: true

  vars:
    couchbase_ports:
      - 8091
      - 8092
      - 8093
      - 8094
      - 11210
      - 11207
      - 11209
      - 18091
      - 18092
      - 18093
      - 4369
      - 21100

  tasks:

    - name: Ensure lsof is installed
      package:
        name: lsof
        state: present

    - name: Check each Couchbase port
      shell: |
        SERVICE=$(lsof -i :{{ item }} | awk 'NR>1 {print $1}' | uniq | paste -sd "," -)
        if [ -n "$SERVICE" ]; then
          echo "CLOSED - Services: [$SERVICE]"
        else
          echo "OPEN"
        fi
      register: port_status
      loop: "{{ couchbase_ports }}"
      changed_when: false

    - name: Summarize port statuses
      set_fact:
        port_summary: >-
          {{ port_summary | default([]) + [item.item ~ ':' ~ item.stdout] }}
      loop: "{{ port_status.results }}"

    - name: Display summarized result
      debug:
        msg: "{{ port_summary | join('\n\n') }}"


    - name: Filter specific port statuses
      set_fact:
        filtered_port_summary: >-
          {{ (port_summary | select('search', '8091:') | list) +
             (port_summary | select('search', '8092:') | list) +
             (port_summary | select('search', '11207:') | list) +
             (port_summary | select('search', '18092:') | list) }}

    - name: Display filtered result
      debug:
        msg: "{{ filtered_port_summary | join('\n\n') }}"
    
