---
- name: Check Couchbase Ports on Remote Server
  hosts: all
  gather_facts: false
  become: true

  vars:
    couchbase_ports:
      - 8091
      - 8092
      - 8093
      - 8094
      - 11210
      - 11207
      - 11209
      - 18091
      - 18092
      - 18093
      - 4369
      - 21100

  tasks:

    - name: Ensure lsof is installed
      package:
        name: lsof
        state: present

    - name: Check each Couchbase port
      shell: |
        SERVICE=$(lsof -i :{{ item }} | awk 'NR>1 {print $1}' | uniq | paste -sd "," -)
        if [ -n "$SERVICE" ]; then
          echo "CLOSED - Services: [$SERVICE]"
        else
          echo "OPEN"
        fi
      register: port_status
      loop: "{{ couchbase_ports }}"
      changed_when: false

    - name: Summarize port statuses
      set_fact:
        port_summary: >-
          {{ port_summary | default([]) + [item.item ~ ':' ~ item.stdout] }}
      loop: "{{ port_status.results }}"

    - name: Display summarized result
      debug:
        msg: "{{ port_summary | join(', ') }}"


    - name: Format port summary into structured list
      set_fact:
        formatted_ports: >-
          {{
            port_summary | map('regex_replace', '^(\\d+):(\\w+)(?: - Services: \\[(.*)\\])?', '{"port": "\\1", "status": "\\2", "services": [\\3]}')
                         | map('from_json')
                         | map('combine', {'services': (item.services | default('') | string).split(',') | map('trim') | list })
                         | list
          }}

  
    - name: Display formatted port summary
      debug:
        var: formatted_ports

         

    
