---
- name: Validate Couchbase Primary Index
  hosts: all
  vars:
    couchbase_host: "54.225.130.193"
    couchbase_user: "Admin"
    couchbase_password: "redhat"
    bucket_name: "bucket1"

  tasks:
    - name: Check if couchbase-cli is installed
      command: /opt/couchbase/bin/couchbase-cli --version
      register: cli_check
      ignore_errors: true

    - name: Fail if couchbase-cli is not found
      fail:
        msg: "couchbase-cli is not installed or not found."
      when: cli_check.rc != 0

    - name: Check if cbq is installed
      command: /opt/couchbase/bin/cbq --version
      register: cbq_check
      ignore_errors: true

    - name: Fail if cbq is not found
      fail:
        msg: "cbq is not installed or not found."
      when: cbq_check.rc != 0

    - name: Validate primary index in Couchbase
      shell: |
        /opt/couchbase/bin/cbq --script="SELECT name FROM system:indexes WHERE is_primary = true AND keyspace_id = '{{ bucket_name }}';" -u {{ couchbase_user }} -p {{ couchbase_password }} -e http://{{ couchbase_host }}:8091
      register: couchbase_query_result
      failed_when: couchbase_query_result.stdout == ""
      changed_when: false

    - name: Display result
      debug:
        msg: >
          Primary index validation {{ 'passed' if couchbase_query_result.stdout != '' else 'failed' }} for bucket '{{ bucket_name }}'.
