---
- name: Ensure #primary index exists
  hosts: all
  vars: 
    couchbase_host: "54.225.130.193" 
    admin_user: "Admin" 
    admin_password: "redhat" 
    bucket: "bucket1" 
    primary_index_name: "#primary" 
    query_port: "8091" 
    rest_port: "8091" 
    username: "couchbase" 
    user_password: "tsm@7200!"
  tasks:
    - name: Check if #primary index exists
      uri:
        url: "http://{{ couchbase_host }}:8091/query/service"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          statement: "SELECT * FROM system:indexes WHERE name = '#primary' AND keyspace_id = '{{ bucket }}'"
        user: "{{ couchbase_user }}"
        password: "{{ couchbase_password }}"
      register: index_check_response

    - name: Debug Index Response
      debug:
        var: index_check_response.json

    - name: Create #primary index if not exists
      uri:
        url: "http://{{ couchbase_host }}:8091/query/service"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          statement: "CREATE PRIMARY INDEX `#primary` ON `{{ bucket_name }}`"
        user: "{{ couchbase_user }}"
        password: "{{ couchbase_password }}"
      when: index_check_response.json.results | length == 0
