---
- name: Validate Couchbase Primary Index
  hosts: all
  vars:
    couchbase_host: "54.225.130.193"
    couchbase_user: "Admin"
    couchbase_password: "redhat"
    bucket_name: "bucket1"

  tasks:
    - name: Validate primary index in Couchbase
      shell: |
        couchbase-cli query --cluster {{ couchbase_host }} \
        --username {{ couchbase_user }} --password {{ couchbase_password }} \
        --query "SELECT name FROM system:indexes WHERE is_primary = true AND keyspace_id = '{{ bucket_name }}';"
      register: couchbase_query_result
      failed_when: couchbase_query_result.stdout == ""
      changed_when: false

    - name: Display result
      debug:
        msg: >
          Primary index validation {{ 'passed' if couchbase_query_result.stdout != '' else 'failed' }} for bucket '{{ bucket_name }}'.
