---
- name: Ansible playbook to create filtered index queries
  hosts: all
  gather_facts: no
  vars:
    index_queries: ""  # This will be provided by the user through the survey
    couchbase_bucket: "travel-sample"
    allowed_indexes: []
    not_allowed_indexes: []

  tasks:
    - name: Use the user input from the survey
      debug:
        msg: "Original index queries: {{ index_queries }}"

    - name: Parse and filter index statements
      set_fact:
        allowed_indexes: >
          {%- set allowed = [] -%}
          {%- for line in index_queries.splitlines() -%}
            {%- if 'where' in line.lower() -%}
              {{ allowed.append(line) }}
            {%- elif 'scope' in line.lower() and '{"defer_build":true}' in line.lower() and 'where' not in line.lower() and 'primary' not in line.lower() -%}
              {{ allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ allowed }}

        not_allowed_indexes: >
          {%- set not_allowed = [] -%}
          {%- for line in index_queries.splitlines() -%}
            {%- if 'where' not in line.lower() and 'field' not in line.lower() and line.strip() != '' and not line.startswith('//') -%}
              {{ not_allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ not_allowed }}

    - name: Display allowed index queries after parsing
      debug:
        msg: "Allowed Index Queries: {{ allowed_indexes }}"

    - name: Display not allowed index queries after parsing
      debug:
        msg: "Not Allowed Index Queries: {{ not_allowed_indexes }}"

    - name: Update defer_build and num_replica properties in allowed indexes
      set_fact:
        updated_queries: >
          {%- set updated = [] -%}
          {%- for line in allowed_indexes -%}
            {%- set updated_line = line | regex_replace('(?i)({\"defer_build\":\\s*(false|true)})', '{\"defer_build\": true, \"num_replica\": 1}') -%}
            {{ updated.append(updated_line) }}
          {%- endfor -%}
          {{ updated | join('\n') }}

    - name: Display updated queries
      debug:
        msg: "Updated Index Queries: {{ updated_queries }}"

    - name: Create allowed indexes
      shell: "{{ couchbase_bin_path }} -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }} -s '{{ item }}'"
      with_items: "{{ updated_queries }}"
      register: index_creation_result
      ignore_errors: true
      no_log: false

    - name: Display index creation results
      debug:
        var: index_creation_result

    - name: Classify not allowed indexes based on creation results
      set_fact:
        not_allowed_indexes: >
          {%- set not_allowed = [] -%}
          {%- for item in index_creation_result.results -%}
            {%- if item.rc != 0 -%}  # Check if the return code is not zero (indicating an error)
              {{ not_allowed.append(item.item) }}  # Append the failed query to not_allowed_indexes
            {%- endif -%}
          {%- endfor -%}
          {{ not_allowed }}

    - name: Display final not allowed index queries
      debug:
        msg: "Final Not Allowed Index Queries: {{ not_allowed_indexes }}"

    - name: Execute deferred_index.sh script
      command: "{{ deffered_index_path }}"
