---
- name: Manage Couchbase indexes
  hosts: all
  become: yes
  tasks:

    # Validate index file existence
    - name: Validate index file existence
      ansible.builtin.stat:
        path: /home/ubuntu/Couchbase_UPS/index_file.txt
      register: index_file_stat

    # Read and decode index file
    - name: Read and decode index file
      ansible.builtin.slurp:
        src: /home/ubuntu/Couchbase_UPS/index_file.txt
      register: index_file_content

    - name: Decode the index file content
      set_fact:
        decoded_index_file_content: "{{ index_file_content.content | b64decode }}"

    # Extract index creation SQL
    - name: Extract index creation SQL
      set_fact:
        index_creation_statements: >-
          {{ decoded_index_file_content | regex_findall(
            '  (?i)CREATE\s+INDEX\s+`[^`]+`\s+ON\s+`[^`]+`(?:\.`[^`]+`)*\s*\(.*?\)\s*(WHERE\s+[^;]*)?\s+USING\s+GSI\s+WITH\s+\{[^}]+\};'
          ) }}

    - name: Debug index creation statements
      debug:
        msg: "{{ index_creation_statements }}"


        
  
    # Filter allowed index creation statements (case-insensitive for WHERE)
    - name: Filter allowed index creation statements
      set_fact:
        allowed_index_creation_statements: "{{ index_creation_statements | select('match', '(?i)CREATE INDEX .*? ON .*?\\..*?\\..*?\\(.*?\\) USING GSI WITH {\"defer_build\":true};') | list }}"

    - name: Debug allowed index creation statements
      debug:
        msg: "{{ allowed_index_creation_statements }}"

    # Validate Couchbase CLI availability
    - name: Validate Couchbase CLI availability
      shell: "/opt/couchbase/bin/cbq --version"
      register: cbq_check
      changed_when: false

    - name: Read file data
      slurp:
        src: /home/ubuntu/Couchbase_UPS/index_file.txt
      register: file_content

    - name: Decode file content
      set_fact:
        file_data: "{{ file_content.content | b64decode | string }}"

    
 

      # Extract primary index names using regex
    - name: Extract primary index names using regex
      set_fact:
        primary_index_names: "{{ file_data | regex_findall('(?i)CREATE PRIMARY INDEX `(primary_index_\\d+)`') }}"

    # - name: Display the primary index names
    #   debug:
    #     msg: "The following indexes are not allowed to be created or built: {{ primary_index_names }}"

    - name: Skip primary index creation if indexes are found
      debug:
        msg: "Skipping primary index creation as the following indexes were found: {{ primary_index_names }}"
      when: primary_index_names | length > 0

    - 
    # Create indexes
    - name: Create allowed indexes
      shell: "/opt/couchbase/bin/cbq -u Admin -p redhat -s '{{ item }}'"
      with_items: "{{ allowed_index_creation_statements }}"
      ignore_errors: true

    # Read contents of index_file.txt
    - name: Read contents of index_file.txt
      ansible.builtin.slurp:
        src: "/home/ubuntu/Couchbase_UPS/index_file.txt"
      register: file_contents

    # Decode file contents
    - name: Decode file contents
      set_fact:
        file_data: "{{ file_contents['content'] | b64decode }}"

   
  

    # Decode file contents (if it's base64 encoded)
    - name: Decode file contents
      set_fact:
        file_data: "{{ file_contents['content'] | b64decode | to_nice_yaml }}"



    # # Execute deferred_index.sh script
    # - name: Execute deferred_index.sh script
    #   command: /home/ubuntu/Couchbase_UPS/deffered_index.sh
    #   args:
    #     chdir: /home/ubuntu/Couchbase_UPS
    #   register: script_output

    # # Debug script output
    # - name: Display script output
    #   debug:
    #     var: script_output.stdout











