---
- name: Validate and Create Couchbase Indexes
  hosts: all
  gather_facts: no
  vars:
    couchbase_host: "127.0.0.1"
    couchbase_bin_path: "/opt/couchbase/bin/cbq"
    couchbase_admin_username: "Admin"
    couchbase_admin_password: "redhat"
    index_queries: ""  # This comes from the Ansible survey
  tasks:

    - name: Validate query syntax
      shell: "{{ couchbase_bin_path }} -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }} --script '{{ index_query }}'"
      register: query_result
      failed_when: query_result.rc != 0
      changed_when: false

    - name: Fail if query is creating a primary index
      fail:
        msg: "Primary index creation is not allowed."
      when: "'CREATE PRIMARY INDEX' in index_query | upper"

    - name: Fail if query does not contain a WHERE clause
      fail:
        msg: "Indexes must have a WHERE clause."
      when: 
        - "'CREATE INDEX' in index_query | upper"
        - "'WHERE' not in index_query | upper"

    - name: Execute valid index query
      shell: "{{ couchbase_bin_path }} -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }} --script '{{ index_query }}'"
      changed_when: true
