---
- name: Create Couchbase Indexes based on index_file.txt
  hosts: all
  become: true
  vars:
    # Couchbase Cluster Credentials
    couchbase_cluster: "http://localhost:8091"
    couchbase_user: "Admin"
    couchbase_password: "redhat"

    # Path to the index creation file
    index_file_path: "/home/ubuntu/Couchbase_UPS/index_file.txt"
    
  tasks:

    - name: Read index creation queries from the file
      ansible.builtin.slurp:
        src: "{{ index_file_path }}"
      register: index_file

    - name: Decode the file content from base64
      set_fact:
        index_queries: "{{ index_file.content | b64decode | regex_findall('\\S.*?\\n') }}"

    - name: Parse index queries and filter allowed queries
      set_fact:
        allowed_queries: []
        not_allowed_queries: []

    - name: Categorize index queries into allowed and not-allowed
      block:
        - name: Loop through each index creation query
          ansible.builtin.set_fact:
            allowed_queries: "{{ allowed_queries + [item] if item is match('^(?!//not-allowed).*') else allowed_queries }}"
            not_allowed_queries: "{{ not_allowed_queries + [item] if item is match('^//not-allowed') else not_allowed_queries }}"
          loop: "{{ index_queries }}"
          loop_control:
            loop_var: item

    - name: Print allowed queries
      ansible.builtin.debug:
        msg: "Allowed Queries: {{ allowed_queries }}"

    - name: Print not-allowed queries
      ansible.builtin.debug:
        msg: "Not Allowed Queries: {{ not_allowed_queries }}"

    # Validate Couchbase CLI availability
    - name: Validate Couchbase CLI availability
      shell: "/opt/couchbase/bin/cbq --version"
      register: cbq_check
      changed_when: false

    # Extract primary index names using regex
    - name: Extract primary index names using regex
      set_fact:
        primary_index_names: "{{ index_queries | regex_findall('(?i)CREATE PRIMARY INDEX `(primary_index_\\d+)`') }}"

    - name: Skip disallowed index statements
      set_fact:
        index_creation_statements_to_process: "{{  index_file.content }}"


    - name: Execute allowed queries on Couchbase
      shell: |
        echo "{{ item }}" | /opt/couchbase/bin/cbq  -u "{{ couchbase_user }}" -p "{{ couchbase_password }}" -c "{{ couchbase_cluster }}"
      loop: "{{ allowed_queries }}"
      when: allowed_queries | length > 0
      notify:
        - Refresh index

  handlers:
    - name: Refresh index
      shell: |
        /opt/couchbase/bin/cbq -u "{{ couchbase_user }}" -p "{{ couchbase_password }}" -c "{{ couchbase_cluster }}" -s "REFRESH INDEXES"
