---
- name: Ansible playbook to create filtered index queries
  hosts: all
  gather_facts: no
  vars:
    index_queries: ""  # Provided by the user through the survey
    couchbase_bucket: "travel-sample"
    allowed_indexes: []
    not_allowed_indexes: []

  tasks:
    - name: Use the user input from the survey
      debug:
        msg: "Original index queries: {{ index_queries }}"

    - name: Parse and filter index statements
      set_fact:
        allowed_indexes: >-
          {{ index_queries.splitlines()
             | select("search", "where")
             | union(index_queries.splitlines() | select("search", '{"defer_build":true}'))
             | reject("search", "primary")
             | list }}
        

        not_allowed_indexes: >
          {%- set not_allowed = [] -%}
          {%- for line in index_queries.splitlines() -%}
            {%- if 'where' not in line.lower() and 'field' not in line.lower() and line.strip() != '' and not line.startswith('//') or '()' in line or line.lower().strip().endswith('using gsi with {"defer_build":true};') or '._default.' in line -%}
              {{ not_allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ not_allowed }}

    - name: Display allowed index queries after parsing
      debug:
        msg: "{{ allowed_indexes }}"

    - name: Display not allowed index queries after parsing
      debug:
        msg: "{{ not_allowed_indexes }}"

    - name: Update defer_build and num_replica properties in allowed indexes (JSON format)
      set_fact:
        updated_queries: >
          {%- set updated = [] -%}
          {%- for line in allowed_indexes -%}
            {%- set updated_line = line | regex_replace('(?i)({"defer_build":\s*(false|true)})', '{"defer_build": true, "num_replica": 1}') -%}
            {{ updated.append(updated_line) }}
          {%- endfor -%}
          {{ updated | join('\n') }}

    - name: Update defer_build and num_replica properties in allowed indexes (formatted query)
      set_fact:
        updated_queries: >
          {%- set updated = [] -%}
          {%- for line in allowed_indexes -%}
            {%- set updated_line = line 
              | regex_replace('(?i)CREATE INDEX', 'CREATE INDEX') 
              | regex_replace('(?i)ON\\s+([a-zA-Z0-9_-]+)', 'ON `\g<1>`') 
              | regex_replace('(?i)WHERE\\s+([^"]+)\\s*=\\s*"([^"]+)"', 'WHERE \g<1> = \'\\2\'') 
              | regex_replace('(?i)USING GSI;', 'USING GSI WITH {"defer_build": true, "num_replica": 1};') 
            -%}
            {{ updated.append(updated_line) }}
          {%- endfor -%}
          {{ updated | join('\n') }}

    - name: Update defer_build property in index creation queries (JSON format)
      set_fact:
        updated_queries: >
          {%- set updated = [] -%}
          {%- for line in index_queries -%}
            {%- set updated_line = line | regex_replace('(?i)(WITH\s*\{)', 'WITH {"defer_build": true, ') -%}
            {{ updated.append(updated_line) }}
          {%- endfor -%}
          {{ updated | join('\n') }}

    - name: Display updated JSON queries
      debug:
        msg: "Updated JSON index queries: {{ updated_queries }}"

    - name: Create allowed indexes (JSON format)
      shell: "{{ couchbase_bin_path }} -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }} -s '{{ item }}'"
      with_items: "{{ updated_queries.split('\n') }}"
      register: index_creation_result
      ignore_errors: true
      no_log: false

    - name: Execute deferred index script
      command: "{{ deffered_index_path }}"
      args:
        chdir: "{{ deffered_index_path | dirname }}"
      register: script_output
