---
- name: Manage Couchbase Index Creation
  hosts: all
  become: yes
  become_user: ubuntu
  gather_facts: false

  vars:
    # index_queries will be provided by the user through the survey
    index_queries: ""

  tasks:

    - name: Use the user input from the survey
      debug:
        msg: "{{ index_queries }}"


    - name: Parse and filter index statements
      set_fact:
        allowed_indexes: >
          {%- set allowed = [] -%}
          {%- for line in index_queries.splitlines() -%}
            {%- if 'where' in line.lower() -%}
              {{ allowed.append(line) }}
            {%- elif 'scope' in line.lower() and '{"defer_build":true}' in line.lower() and 'where' not in line.lower() and 'primary' not in line.lower() -%}
              {{ allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ allowed }}
      # Filters allowed index queries based on conditions

    - name: Update defer_build and num_replica properties in allowed indexes
      set_fact:
        updated_queries: >
          {%- set updated = [] -%}
          {%- for line in allowed_indexes -%}
            {%- set updated_line = line | regex_replace('(?i)({\"defer_build\":\\s*(false|true)})', '{\"defer_build\": true, \"num_replica\": 1}') -%}
            {{ updated.append(updated_line) }}
          {%- endfor -%}
          {{ updated | join('\n') }}
      # Updates the defer_build and num_replica properties for allowed index queries

    - name: Display the updated queries for verification
      debug:
        msg: "{{ updated_queries }}"
      # Displays the updated index creation queries for verification

    - name: Create allowed indexes using cbq
      shell: >
        echo "{{ item }}" | {{ couchbase_bin_path }}/cbq -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }} -s '{{ couchbase_bucket }}'
      with_items: "{{ updated_queries.splitlines() }}"
      register: index_creation_result
      ignore_errors: false
      no_log: false
      # Passes each query individually to cbq for execution

    - name: Show cbq command output
      debug:
        msg: "{{ index_creation_result }}"
      # Shows the result of the cbq command execution

    - name: Execute test.sh script
      command: "{{ test_script_path }}"
      args:
        chdir: "{{ test_script_path | dirname }}"
      register: script_output
      # Executes the test.sh script after index creation
