---
- name: Create Couchbase Index
  hosts: all
  gather_facts: false
  tasks:
    - name: Read index file
      slurp:
        src: /home/ubuntu/Couchbase_UPS/index_file.txt
      register: index_file_content

    - name: Check conditions and create index
      shell: |
        INDEX_NAME=$(echo "{{ index_file_content['content'] | b64decode }}" | grep -oP '(?<=INDEX ).*(?= ON)')
        if [[ -n "$INDEX_NAME" && $(echo "{{ index_file_content['content'] | b64decode }}" | grep -q 'deferred_build:true') && $(echo "{{ index_file_content['content'] | b64decode }}" | grep -q 'WHERE') ]]; then
          /opt/couchbase/bin/cbq localhost:8091 -u Admin -p redhat --stats all --index {{ INDEX_NAME }}
        fi
      register: create_index

    - debug:
        msg: "Index creation result: {{ create_index.stdout }}"
