---
- name: Couchbase Index Control Playbook
  hosts: all
  become: true
  tasks:

    - name: Read the index creation file
      ansible.builtin.slurp:
        src: /home/ubuntu/Couchbase_UPS/index_file.txt
      register: index_file_content

    - name: Decode the index file content and split into lines
      ansible.builtin.set_fact:
        index_queries: "{{ index_file_content['content'] | b64decode | split('\n') }}"

    - name: Filter allowed index creation queries
      ansible.builtin.set_fact:
        allowed_queries: "{{ index_queries | select('match', '^CREATE INDEX .+ USING GSI WITH \\{.*defer_build:true.*\\}') | list }}"

    - name: Disallow queries with missing `defer_build:true` or invalid WHERE clauses
      ansible.builtin.set_fact:
        disallowed_queries: "{{ index_queries | select('match', '^CREATE INDEX .+ USING GSI(?!.*defer_build:true.*).*$') | list }}"

    - name: Filter valid WHERE clauses
      ansible.builtin.set_fact:
        valid_where_clauses: "{{ index_queries | select('match', '^CREATE INDEX .+ WHERE .*(IS NOT NULL|=|IN|WherE).*') | list }}"

    - name: Check for invalid queries without required conditions
      ansible.builtin.debug:
        msg: |
          Invalid queries:
          {{ disallowed_queries }}

    - name: Check for valid queries (with correct WHERE conditions)
      ansible.builtin.debug:
        msg: |
          Valid queries:
          {{ valid_where_clauses }}

    - name: Save allowed queries to a new file
      ansible.builtin.copy:
        dest: /home/ubuntu/Couchbase_UPS/allowed_index_queries.txt
        content: "{{ allowed_queries | join('\n') }}"

    - name: Save disallowed queries to a new file
      ansible.builtin.copy:
        dest: /home/ubuntu/Couchbase_UPS/disallowed_index_queries.txt
        content: "{{ disallowed_queries | join('\n') }}"
