---
- name: Manage Couchbase Index Creation
  hosts: all
  become: yes
  become_user: ubuntu
  #connection: local
  gather_facts: false

  vars:
    index_file_path: "/home/ubuntu/Couchbase_UPS/index_file.txt"
    allowed_indexes: []
    not_allowed_indexes: []

  tasks:
    - name: Read the index file
      slurp:
        src: "{{ index_file_path }}"
      register: index_file_content

    - name: Parse and filter index statements
      set_fact:
        allowed_indexes: >
          {%- set allowed = [] -%}
          {%- for line in (index_file_content.content | b64decode).splitlines() -%}
            {%- if 'where' in line.lower() -%}
              {{ allowed.append(line) }}
            {%- elif 'scope' in line.lower() and '{"defer_build":true}' in line.lower() and 'where' not in line.lower() and 'primary' not in line.lower() -%}
              {{ allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ allowed }}

        not_allowed_indexes: >
          {%- set not_allowed = [] -%}
          {%- for line in (index_file_content.content | b64decode).splitlines() -%}
            {%- if 'where' not in line.lower() and 'scope' not in line.lower() and '{"defer_build":true}' not in line.lower() and 'primary' not in line.lower() and line.strip() != '' and not line.startswith('//') -%}
              {{ not_allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ not_allowed }}

    - name: Debug allowed index statements
      debug:
        msg: "{{ item }}"
      loop: "{{ allowed_indexes }}"
      loop_control:
        loop_var: item

    - name: Debug not-allowed index statements
      debug:
        msg: "{{ item }}"
      loop: "{{ not_allowed_indexes }}"
      loop_control:
        loop_var: item

    - name: Execute allowed index statements
      shell: "/opt/couchbase/bin/cbq -u Admin -p redhat -q'{{ item }}'"
      with_items: "{{ allowed_indexes }}"
      register: index_creation_results

    - name: Debug index creation results
      debug:
        var: index_creation_results
