---
- name: Validate Index Creation Statements from File
  hosts: all  # Replace with your target host or group
  gather_facts: no
  tasks:
    - name: Read index creation statements from file
      slurp:
        src: /home/ubuntu/Couchbase_UPS/index_file.txt
      register: index_file_content

    - name: Decode and split index statements
      set_fact:
        index_statements: "{{ index_file_content['content'] | b64decode | to_nice_yaml | split('\n') }}"

    - name: Validate index creation statements
      debug:
        msg: "{{ item }}"
      loop: "{{ index_statements }}"
      when: >
        (item is search('CREATE INDEX') or item is search('CREATE PRIMARY INDEX')) and
        (item is search('defer_build": true') or item is search('defer_build": false')) and
        not (item is search('defer_build": false') or item is search('WHERE') and item is search('idx_docType_04'))
      register: valid_indexes

    - name: Log valid index creation statements
      debug:
        msg: "Valid index creation: {{ item }}"
      loop: "{{ valid_indexes.results | selectattr('msg', 'defined') | map(attribute='msg') | list }}"
