---
- name: Create Couchbase Index
  hosts: localhost
  gather_facts: false
  tasks:


    - name: Check if the index file exists 
      stat: 
        path: /home/ubuntu/Couchbase_UPS/index_file.txt 
      register: file_status 
      
    - debug: 
        msg: "File exists: {{ file_status.stat.exists }}; Readable: {{ file_status.stat.readable }}"
   
    - name: Read index file
      slurp:
        src: /home/ubuntu/Couchbase_UPS/index_file.txt
      register: index_file_content

    - name: Extract index name
      set_fact:
        index_content: "{{ index_file_content['content'] | b64decode }}"
        index_name: "{{ index_content | regex_search('INDEX\\s+(\\w+)\\s+ON', '\\1') }}"

    - name: Check conditions and create index
      shell: |
        if [[ -n "{{ index_name }}" && "{{ index_content }}" =~ 'deferred_build:true' && "{{ index_content }}" =~ 'WHERE' ]]; then
          couchbase-cli cbstats localhost:8091 -u USERNAME -p PASSWORD --stats all --index {{ index_name }}
        fi
      register: create_index

    - debug:
        msg: "Index creation result: {{ create_index.stdout }}"
