---
- name: Manage Couchbase Index Creation
  hosts: all
  become: yes
  become_user: ubuntu
  gather_facts: false


  
  tasks:
    - name: Read the index file
      slurp:
        src: "{{ index_file_path }}"
      register: index_file_content

    - name: Parse and filter index statements
      set_fact:
        allowed_indexes: >
          {%- set allowed = [] -%}
          {%- for line in (index_file_content.content | b64decode).splitlines() -%}
            {%- if 'where' in line.lower() -%}
              {{ allowed.append(line) }}
            {%- elif 'shippingNo' in line.lower() and 'container1' in line.lower() and 'facilityNo' not in line.lower() -%}
              {{ allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ allowed }}
     
        not_allowed_indexes: >
          {%- set not_allowed = [] -%}
          {%- for line in (index_file_content.content | b64decode).splitlines() -%}
            {%- if 'travel-sample.scopeB.collection3()' not in line.lower() and 'collection3()' not in line.lower() and line.strip() != '' and not line.startswith('//') -%}
              {{ not_allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ not_allowed }}

    - name: Debug allowed index statements
      debug:
        msg: "{{ item }}"
      loop: "{{ allowed_indexes }}"
      loop_control:
        loop_var: item

    - name: Debug not-allowed index statements
      debug:
        msg: "{{ item }}"
      loop: "{{ not_allowed_indexes }}"
      loop_control:
        loop_var: item

    - name: Create allowed indexes
      shell: "{{ couchbase_bin_path }} -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }} -s '{{ item }}'"
      with_items: "{{ allowed_indexes }}"
      register: index_creation_result
      ignore_errors: true

    - name: Debug index creation results
      debug:
        var: index_creation_result

    - name: Execute test.sh script
      command: "{{ test_script_path }}"
      args:
        chdir: "{{ test_script_path | dirname }}"
      register: script_output
