---
- name: Create valid Couchbase indexes
  hosts: all  # Adjust this to your specific Couchbase host or group
  become: yes
  become_user: ubuntu
  vars:
    couchbase_host: "localhost"  # Replace with your Couchbase hostname or IP
    couchbase_username: "admin"  # Replace with your Couchbase admin username
    couchbase_password: "password"  # Replace with your Couchbase admin password
    cbq_path: "/opt/couchbase/bin/cbq"  # Adjust the path to the cbq command if it's not in the default PATH

  tasks:
    - name: Read index file content
      ansible.builtin.slurp:
        src: /home/ubuntu/Couchbase_UPS/index_file.txt
      register: index_file_content

    - name: Decode base64 content and split into lines using regex
      set_fact:
        index_lines: "{{ index_file_content.content | b64decode | regex_findall('\\S.*') }}"

    - name: Filter valid index creation queries
      set_fact:
        valid_queries: |
          {%- set valid = [] -%}
          {%- for line in index_lines -%}
            {%- if line is search('CREATE INDEX') and line is not search('PRIMARY INDEX') -%}
              {%- if line is search('"defer_build":true') -%}
                {%- if line is search('WHERE') -%}
                  {%- do valid.append(line) -%}
                {%- endif -%}
              {%- endif -%}
            {%- endif -%}
          {%- endfor -%}
          {{ valid }}

    - name: Show filtered valid index creation queries
      debug:
        msg: "{{ valid_queries }}"

    - name: Create the valid indexes using shell (cbq)
      shell: |
        echo "{{ item }}" | {{ cbq_path }} -u {{ couchbase_username }} -p {{ couchbase_password }} -s {{ couchbase_host }}
      loop: "{{ valid_queries }}"
      when: valid_queries | length > 0
      register: index_creation_result
      ignore_errors: yes  # Optional, ignore errors if you don't want the playbook to fail on a query

    - name: Show result of index creation
      debug:
        msg: "{{ index_creation_result }}"
