---
- name: Validate and Create Couchbase Indexes
  hosts: all
  gather_facts: no
  vars:
    couchbase_host: "127.0.0.1"
    couchbase_bin_path: "/opt/couchbase/bin/cbq"
    couchbase_admin_username: "Admin"
    couchbase_admin_password: "redhat"
    index_queries: []  # This comes from the Ansible survey

  tasks:
    - name: Initialize Query Lists
      set_fact:
        allowed_queries: []
        not_allowed_queries: []

    - name: Identify Allowed Queries (Basic Keyword Filtering)
      set_fact:
        allowed_queries: "{{ allowed_queries + [item] }}"
      when: 
        - "not item | regex_search('CREATE PRIMARY INDEX', ignorecase=True)"
        - "item | regex_search('CREATE INDEX', ignorecase=True)"
        - "item | regex_search('WHERE', ignorecase=True)"
        - "item | regex_search('ON\\s+[^()]+\\([^)]*\\)', ignorecase=True)"  # Ensures valid ON syntax
      with_items: "{{ index_queries }}"

    - name: Identify Not Allowed Queries
      set_fact:
        not_allowed_queries: "{{ not_allowed_queries + [item] }}"
      when: 
        - "item not in allowed_queries"
      with_items: "{{ index_queries }}"

    - name: Debug - Allowed Queries After Initial Filtering
      debug:
        msg: "Allowed Query: {{ item }}"
      with_items: "{{ allowed_queries }}"

    - name: Debug - Not Allowed Queries After Initial Filtering
      debug:
        msg: "Not Allowed Query: {{ item }}"
      with_items: "{{ not_allowed_queries }}"

    - name: Validate Allowed Queries Syntax Using cbq
      shell: "{{ couchbase_bin_path }} -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }} -s '{{ item }}'"
      with_items: "{{ allowed_queries }}"
      register: syntax_check
      ignore_errors: yes

    - name: Reclassify Queries Based on Syntax Validation
      set_fact:
        allowed_queries: "{{ allowed_queries | difference([item.item]) }}"
        not_allowed_queries: "{{ not_allowed_queries + [item.item] }}"
      when: item.rc != 0
      with_items: "{{ syntax_check.results }}"

    - name: Debug - Allowed Queries After Syntax Check
      debug:
        msg: "Allowed Query (Final): {{ item }}"
      with_items: "{{ allowed_queries }}"

    - name: Debug - Not Allowed Queries After Syntax Check
      debug:
        msg: "Not Allowed Query (Final): {{ item }}"
      with_items: "{{ not_allowed_queries }}"

    - name: Ensure defer_build and num_replica in Allowed Queries
      set_fact:
        updated_queries: >-
          {{
            allowed_queries | map('regex_replace', 
              '(?<=\{)(?!.*"defer_build"\s*:\s*true)(?=.*"num_replica"\s*:\s*1)', 
              '"defer_build":true,') 
            | map('regex_replace', 
              '(?<=\{)(?!.*"num_replica"\s*:\s*1)(?=.*"defer_build"\s*:\s*true)', 
              '"num_replica":1,') 
            | map('regex_replace', 
              '(?<=\{)(?!.*"defer_build"\s*:\s*true)(?!.*"num_replica"\s*:\s*1)', 
              '"defer_build":true, "num_replica":1,')
            | list
          }} 

    - name: Debug - Updated Queries
      debug:
        msg: "Updated Query: {{ item }}"
      with_items: "{{ updated_queries }}"

    - name: Execute Allowed Index Queries
      shell: "{{ couchbase_bin_path }} -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }} -s '{{ item }}'"
      with_items: "{{ updated_queries }}"
      when: allowed_queries | length > 0
      register: query_result

    - name: Execute Deferred Index Script
      command: "{{ deffered_index_path }}"
      args:
        chdir: "{{ deffered_index_path | dirname }}"
      register: script_output
      when: deffered_index_path is defined
