---
- name: Ansible playbook to create filtered index queries
  hosts: all
  gather_facts: no
  vars:
    # index_queries will be provided by the user through the survey
    index_queries: ""
    couchbase_bucket: "travel-sample"
    allowed_indexes: []
    not_allowed_indexes: []

  tasks:
    - name: Use the user input from the survey
      debug:
        msg: "Original index queries: {{ index_queries }}"

    - name: Parse and filter index statements
      set_fact:
        allowed_indexes: >
          {%- set allowed = [] -%}
          {%- for line in index_queries.splitlines() -%}
            {%- if 'where' in line.lower() and '()' not in line and not line.lower().strip().endswith('using gsi with {"defer_build":true};') and '._default.' not in line -%}
              {{ allowed.append(line) }}
            {%- elif ('scope' in line.lower()) and '{"defer_build":true}' in line.lower() and 'where' not in line.lower() and 'primary' not in line.lower() and '()' not in line -%}
              {{ allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ allowed }}

        not_allowed_indexes: >
          {%- set not_allowed = [] -%}
          {%- for line in index_queries.splitlines() -%}
            {%- if 'where' not in line.lower() and 'field' not in line.lower() and line.strip() != '' and not line.startswith('//') or '()' in line or line.lower().strip().endswith('using gsi with {"defer_build":true};') or '._default.' in line -%}
              {{ not_allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ not_allowed }}

    - name: Display allowed index queries after parsing
      debug:
        msg: "{{ allowed_indexes }}"

    - name: Display not allowed index queries after parsing
      debug:
        msg: "{{ not_allowed_indexes }}"

    - name: Update defer_build and num_replica properties in allowed indexes
      set_fact:
        updated_queries: >
          {%- set updated = [] -%}
          {%- for line in allowed_indexes -%}
            {%- set updated_line = line | regex_replace('(?i)({"defer_build":\s*(false|true)})', '{"defer_build": true, "num_replica": 1}') -%}
            {{ updated.append(updated_line) }}
          {%- endfor -%}
          {{ updated | join('\n') }}

    - name: Update defer_build and num_replica properties in allowed indexes
      set_fact:
        updated1_queries: >
          {%- set updated = [] -%}
          {%- for line in allowed_indexes -%}
            {%- if 'CREATE INDEX' in line and 'USING GSI' in line -%}
              {%- set updated_line = line | regex_replace('(?i)(USING GSI;)', 'WITH {"defer_build": true, "num_replica": 1} USING GSI;') -%}
              {{ updated.append(updated_line) }}
            {%- else -%}
              {{ updated.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ updated | join('\n') }}

    - name: Display updated queries
      debug:
        msg: "Updated index queries: {{ updated_queries 

    - name: Display updated queries
      debug:
        msg: "Updated index queries: {{ updated1_queries }}"

    - name: Create allowed indexes
      shell: "{{ couchbase_bin_path }} -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }} -s '{{ item }}'"
      with_items: "{{ updated_queries }}"
      register: index_creation_result
      ignore_errors: true
      no_log: false

    - name: Create allowed indexes
      shell: "{{ couchbase_bin_path }} -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }} -s '{{ item }}'"
      with_items: "{{ updated1_queries }}"
      register: index_creation_result
      ignore_errors: true
      no_log: false

    - name: Execute deffered_index.sh script
      command: "{{ deffered_index_path }}"
      args:
        chdir: "{{ deffered_index_path | dirname }}"
      register: script_output
