- name: Manage Couchbase Index Creation
  hosts: all
  become: yes
  become_user: ubuntu
  gather_facts: false

  vars:
    index_file_path: "/home/ubuntu/Couchbase_UPS/index_file.txt"
    allowed_indexes: []
    not_allowed_indexes: []

  tasks:
    - name: Read the index file
      slurp:
        src: "{{ index_file_path }}"
      register: index_file_content

    - name: Parse and filter index statements
      set_fact:
        allowed_indexes: >
          {%- set allowed = [] -%}
          {%- for line in (index_file_content.content | b64decode).splitlines() -%}
            {%- if 'where' in line.lower() -%}
              {{ allowed.append(line) }}
            {%- elif 'scope' in line.lower() and '{"defer_build":true}' in line.lower() and 'where' not in line.lower() and 'primary' not in line.lower() -%}
              {{ allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ allowed }}

        not_allowed_indexes: >
          {%- set not_allowed = [] -%}
          {%- for line in (index_file_content.content | b64decode).splitlines() -%}
            {%- if 'where' not in line.lower() and 'field' not in line.lower() and line.strip() != '' and not line.startswith('//') -%}
              {{ not_allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ not_allowed }}

    - name: Debug allowed index statements
      debug:
        msg: "{{ item }}"
      loop: "{{ allowed_indexes }}"
      loop_control:
        loop_var: item

    - name: Debug not-allowed index statements
      debug:
        msg: "{{ item }}"
      loop: "{{ not_allowed_indexes }}"
      loop_control:
        loop_var: item

    - name: Debug allowed indexes
      debug:
        msg: "Allowed indexes: {{ allowed_indexes }}"

    - name: Check if there are allowed indexes
      fail:
        msg: "No allowed indexes found. Please check the index file."
      when: allowed_indexes | length == 0    

    - name: Create allowed indexes
      shell: "/opt/couchbase/bin/cbq -u Admin -p redhat -s '{{ item }}'"
      with_items: "{{ allowed_indexes }}"
      register: index_creation_result
      ignore_errors: true

    - name: Debug index creation results
      debug:
        var: index_creation_result

    - name: Build allowed indexes
      shell: "/opt/couchbase/bin/cbq -u Admin -p redhat -s 'BUILD INDEX ON travel-sample({{ item }})'"
      with_items: "{{ allowed_indexes }}"
      register: build_index_result
      ignore_errors: true

    - name: Debug build index results
      debug:
        var: build_index_result

    - name: Check for errors in index creation
      debug:
        msg: "Error in creating index: {{ item.stderr }}"
      loop: "{{ index_creation_result.results }}"
      when: item.rc != 0

    - name: Check for errors in building indexes
      debug:
        msg: "Error in building index: {{ item.stderr }}"
      loop: "{{ build_index_result.results }}"
      when: item.rc != 0
