---
- name: Skip unwanted index creation commands
  hosts: all
  gather_facts: no
  tasks:
    - name: Read index file content
      ansible.builtin.slurp:
        src: /home/ubuntu/Couchbase_UPS/index_file.txt
      register: file_content

    - name: Set filtered index creation queries using regex
      set_fact:
        filtered_queries: "{{ file_content.content | b64decode | regex_findall('^(?!.*(USING GSI|WITH {\"defer_build\":|docType;}).*$).+', multiline=True) }}"

    - name: Print filtered queries to the playbook log
      debug:
        msg: "Filtered Index Queries: {{ filtered_queries }}"

    - name: Write filtered queries back to a new file
      ansible.builtin.copy:
        dest: /home/ubuntu/Couchbase_UPS/filtered_index_file.txt
        content: "{{ filtered_queries | join('\n') }}"
        mode: '0644'
