---
- name: Ansible playbook to create filtered index queries
  hosts: all
  gather_facts: no
  vars:
    # index_queries will be provided by the user through the survey
    index_queries: ""

    couchbase_bucket: "travel-sample"

  tasks:
    - name: Use the user input from the survey
      debug:
        msg: "Original index queries: {{ index_queries }}"

    - name: Parse and filter index statements
      set_fact:
        allowed_indexes: >
          {%- set allowed = [] -%}
          {%- for line in index_queries.splitlines() -%}
            {%- if 'where' in line.lower() -%}
              {{ allowed.append(line) }}
            {%- elif 'scope' in line.lower() and '{"defer_build":true}' in line.lower() and 'where' not in line.lower() and 'primary' not in line.lower() -%}
              {{ allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ allowed }}

    - name: Display allowed index queries after parsing
      debug:
        msg: "Filtered index queries: {{ allowed_indexes }}"

    - name: Use filtered index queries to create the indexes
      # Replace this task with the actual implementation for creating indexes in Couchbase or your target system
      debug:
        msg: "Creating indexes: {{ allowed_indexes }}"
        
    # You can add additional tasks here for further processing based on allowed_indexes, such as executing Couchbase index creation.
