---
- name: Ansible playbook to create filtered index queries
  hosts: all
  gather_facts: no
  vars:
    index_queries: ""  # Provided by the user through the survey
    couchbase_bucket: "travel-sample"
    allowed_indexes: []
    not_allowed_indexes: []
    updated_queries: []

  tasks:
    # Debug the original input queries
    - name: Debug original input index queries
      debug:
        msg: "Index queries provided: {{ index_queries }}"

    # Filter allowed index queries
    - name: Parse and filter allowed index statements
      set_fact:
        allowed_indexes: >-
          {{ index_queries.splitlines()
             | select("search", "where")
             | union(index_queries.splitlines() | select("search", '{"defer_build":true}'))
             | reject("search", "primary")
             | list }}

    # Debug allowed index queries
    - name: Debug allowed index queries
      debug:
        msg: "Allowed index queries: {{ allowed_indexes }}"

    # Filter not allowed index queries
    - name: Parse and filter not allowed index statements
      set_fact:
        not_allowed_indexes: >-
          {{ index_queries.splitlines()
             | reject("search", "where")
             | reject("search", "field")
             | reject("search", '{"defer_build":true}')
             | reject("match", "^//")
             | reject("equalto", "")
             | list }}

    # Debug not allowed index queries
    - name: Debug not allowed index queries
      debug:
        msg: "Not allowed index queries: {{ not_allowed_indexes }}"

    # Update defer_build and num_replica properties in allowed indexes
    - name: Update defer_build and num_replica properties in allowed indexes
      set_fact:
        updated_queries: >-
          {{ allowed_indexes
             | map("regex_replace", "(?i)({\"defer_build\":\\s*(false|true)})", '{"defer_build": true, "num_replica": 1}')
             | map("regex_replace", "(?i)(USING GSI WITH\\s*\\{)", "USING GSI WITH {\"defer_build\": true, \"num_replica\": 1,")
             | list }}

    # Debug updated JSON queries
    - name: Debug updated JSON index queries
      debug:
        msg: "Updated JSON index queries: {{ updated_queries }}"

    # Create allowed indexes (JSON format)
    - name: Create allowed indexes
      shell: >
        cbq -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }}
        -s '{{ item }}'
      with_items: "{{ updated_queries }}"
      register: index_creation_result
      ignore_errors: true

    # Debug index creation results
    - name: Debug index creation results
      debug:
        var: index_creation_result

    # Execute deferred index script (if applicable)
    - name: Execute deferred index script
      command: "{{ deferred_index_path }}"
      args:
        chdir: "{{ deferred_index_path | dirname }}"
      register: script_output

    # Debug deferred index script output
    - name: Debug deferred index script output
      debug:
        var: script_output
