---
- name: Ansible playbook to create filtered index queries
  hosts: all
  gather_facts: no
  vars:
    index_queries: ""  # Provided by the user through the survey
    couchbase_bucket: "travel-sample"
    allowed_indexes: []
    not_allowed_indexes: []

  tasks:
    - name: Use the user input from the survey
      debug:
        msg: "Original index queries: {{ index_queries }}"

    - name: Parse and filter allowed index statements
      set_fact:
        allowed_indexes: >
          {%- set allowed = [] -%}
          {%- for line in index_queries.splitlines() -%}
            {%- if 'where' in line.lower() -%}
              {{ allowed.append(line) }}
            {%- elif 'scope' in line.lower() and '{"defer_build":true}' in line.lower() and 'where' not in line.lower() and 'primary' not in line.lower() -%}
              {{ allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ allowed }}

    - name: Parse and filter not allowed index statements
      set_fact:
        not_allowed_indexes: >
          {%- set not_allowed = [] -%}
          {%- for line in index_queries.splitlines() -%}
            {%- if 'where' not in line.lower() and 'field' not in line.lower() and line.strip() != '' and not line.startswith('//') -%}
              {{ not_allowed.append(line) }}
            {%- endif -%}
          {%- endfor -%}
          {{ not_allowed }}

    - name: Display allowed index queries after parsing
      debug:
        msg: "Allowed index queries: {{ allowed_indexes }}"

    - name: Display not allowed index queries after parsing
      debug:
        msg: "Not allowed index queries: {{ not_allowed_indexes }}"

    - name: Update defer_build and num_replica properties in allowed indexes
      set_fact:
        updated_queries: >
          {%- set updated = [] -%}
          {%- for line in allowed_indexes -%}
            {%- set updated_line = line | regex_replace('(?i)({\"defer_build\":\\s*(false|true)})', '{\"defer_build\": true, \"num_replica\": 1}') -%}
            {{ updated.append(updated_line) }}
          {%- endfor -%}
          {{ updated | join('\n') }}

    - name: Update defer_build and num_replica properties in allowed indexes
      set_fact:
        updated_queries: >
          {%- set updated = [] -%}
          {%- for line in allowed_indexes -%}
            {%- set updated_line = line | regex_replace('(?i)(USING GSI WITH\\s*\\{)', 'USING GSI WITH {\"defer_build\": true, \"num_replica\": 1,') -%}
            {{ updated.append(updated_line) }}
          {%- endfor -%}
          {{ updated | join('\n') }}

    - name: Display updated JSON queries
      debug:
        msg: "Updated JSON index queries: {{ updated_queries }}"

    - name: Create allowed indexes (JSON format)
      shell: "{{ couchbase_bin_path }} -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }} -s '{{ item }}'"
      with_items: "{{ updated_queries.split('\n') }}"
      register: index_creation_result
      ignore_errors: true
      no_log: false

    - name: Execute deferred index script
      command: "{{ deffered_index_path }}"
      args:
        chdir: "{{ deffered_index_path | dirname }}"
      register: script_output
