---
- name: Manage Couchbase indexes
  hosts: all
  become: yes
  tasks:
    - name: Read index queries from file
      slurp:
        src: /home/ubuntu/Couchbase_UPS/index_file.txt
      register: index_queries

    - name: Parse index queries
      set_fact:
        queries: "{{ index_queries['content'] | b64decode | split('\n') }}"

    - name: Filter allowed queries
      set_fact:
        allowed_queries: >-
          {{
            queries
            | select('search', r'allowed')
            | reject('search', r'not-allowed')  # Exclude queries marked as not-allowed
            | map('regex_replace', r'#.*$', '')  # Remove comments
            | map('trim')  # Trim whitespace
            | select('!=', '')  # Remove empty lines
          }}

    - name: Further validate queries
      set_fact:
        validated_queries: >-
          {{
            allowed_queries
            | reject('search', r'defer_build.true.(?<!WHERE.*)')  # Reject deferred queries without WHERE clause
            | reject('search', r'CREATE\s+PRIMARY\s+INDEX')  # Reject primary indexes
            | list
          }}

    - name: Execute validated queries
      command: >
        couchbase-cli query --cluster localhost:8091 --user Admin
        --password redhat --statement "{{ item }}"
      loop: "{{ validated_queries }}"
      register: query_results
      failed_when: "'error' in item.stdout.lower()"

    - name: Log query execution results
      debug:
        msg: "{{ item.stdout }}"
      loop: "{{ query_results.results }}"
      when: "'stdout' in item"

    - name: Build deferred indexes
      command: >
        couchbase-cli query --cluster localhost:8091 --user Admin
        --password redhat --statement "BUILD INDEX ON travel-sample
      when: "'defer_build' in item and 'true' in item"
      register: build_results

    - name: Log deferred build results
      debug:
        msg: "{{ item.stdout }}"
      loop: "{{ build_results.results }}"

  
  
