---
- name: Add defer_build and num_replica to Couchbase index queries
  hosts: all
  tasks:
    - name: Define Couchbase index query
      set_fact:
        index_query: 'Create index Secondary_index_01 ON travel-sample.scopeB.collection3(field2) WHERE field2 = "value2" USING GSI;'
    
    - name: Check and add defer_build and num_replica if missing
      set_fact:
        modified_index_query: "{{ index_query | regex_replace('(USING GSI;)', '{ \"defer_build\": true, \"num_replica\": 1 } \\1') }}"
    
    - name: Display the modified query
      debug:
        msg: "{{ modified_index_query }}"
