---
- name: Validate and Create Couchbase Indexes
  hosts: all
  gather_facts: no
  vars:
    couchbase_bin_path: "/path/to/couchbase_bin"
    couchbase_admin_username: "admin"
    couchbase_admin_password: "password"
    index_queries: []
    INDEX_NAME: []
    deffered_index_path: "/path/to/deffered_index.sh"
    default_index_path: "/path/to/default_index.sh"

  tasks:
    - name: Identify and categorize index queries
      set_fact:
        allowed_queries: []
        not_allowed_queries: []
        queries_exceeding_fields: []

    - name: Validate syntax of index queries
      shell: "{{ couchbase_bin_path }} -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }} -s 'EXPLAIN {{ item }}'"
      register: syntax_check
      with_items: "{{ index_queries }}"
      failed_when: "'syntax error' in syntax_check.stderr or 'syntax error' in syntax_check.stdout"

    - name: Identify queries exceeding field limits
      set_fact:
        queries_exceeding_fields: "{{ queries_exceeding_fields + [item] }}"
      when:
        - "item is search('CREATE INDEX')"
        - "item is search('ON\\s*[^()]+\\(([^)]+)\\)')"  # Extracts fields inside ON(...)
        - "(item | regex_replace('.*ON\\s*[^()]+\\(([^)]+)\\).*', '\\1') | trim | replace('`', '') | split(',') | list | length) > 2"
      with_items: "{{ index_queries }}"


    - name: Identify not allowed queries
      set_fact:
        not_allowed_queries: "{{ not_allowed_queries + [item] }}"
      when:
        - "item | regex_search('CREATE PRIMARY INDEX', ignorecase=True) or not item | regex_search('WHERE', ignorecase=True)"
      with_items: "{{ index_queries }}"

    - name: Display blocked queries due to exceeding field limit
      debug:
        msg: "\033[1;31mQuery exceeds field limit: {{ item }}\033[0m"
      with_items: "{{ queries_exceeding_fields }}"
      when: queries_exceeding_fields | length > 0

    - name: Filter out queries exceeding field limits
      set_fact:
        allowed_queries: "{{ allowed_queries + [item] }}"
      when: 
        - "item not in queries_exceeding_fields"
        - "item not in not_allowed_queries"
      with_items: "{{ index_queries }}"

    - name: Debug - Allowed Queries
      debug:
        msg: "\033[32mAllowed Index Query: {{ item }}\033[0m"
      with_items: "{{ allowed_queries }}"

    - name: Remove semicolon using regex
      set_fact:
        allowed_queries_clean: "{{ allowed_queries | map('regex_replace', ';\\s*$', '') | list }}"

    - name: Ensure WITH clause in index queries
      set_fact:
        updated_queries: >-
          {{
            allowed_queries_clean | map('regex_replace', 
              'WITH\\s*\\{[^}]*\\}', 
              'WITH {"defer_build": true, "num_replica": 1}') 
            | map('regex_replace', 
              '(?i)(?!.*WITH\\s*\\{.*\\})$', 
              ' WITH {"defer_build": true, "num_replica": 1}') 
            | list
          }}

    - name: Debug - Updated Index Queries
      debug:
        msg: "\033[32mUpdated Query: {{ item }}\033[0m"
      with_items: "{{ updated_queries }}"

    - name: Execute allowed index queries
      shell: "{{ couchbase_bin_path }} -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }} -s '{{ item }}'"
      with_items: "{{ updated_queries }}"
      when: updated_queries | length > 0
      register: query_result
      ignore_errors: no

    - name: Execute deferred_index.sh script
      command: "{{ deffered_index_path }}"
      args:
        chdir: "{{ deffered_index_path | dirname }}"
      register: script_output
