---
- name: Manage Couchbase indexes
  hosts: all
  become: yes
  tasks:

    # Validate index file existence
    - name: Validate index file existence
      ansible.builtin.stat:
        path: /home/ubuntu/Couchbase_UPS/index_file.txt
      register: index_file_stat

    - name: Fail if index file does not exist
      fail:
        msg: "Index file does not exist at /home/ubuntu/Couchbase_UPS/index_file.txt"
      when: not index_file_stat.stat.exists

    # Read and decode index file
    - name: Read and decode index file
      ansible.builtin.slurp:
        src: /home/ubuntu/Couchbase_UPS/index_file.txt
      register: index_file_content

    - name: Decode the index file content
      set_fact:
        decoded_index_file_content: "{{ index_file_content.content | b64decode }}"

    # Extract index creation SQL
    - name: Extract index creation SQL
      set_fact:
        index_creation_statements: "{{ decoded_index_file_content | regex_findall('(?i)CREATE INDEX.*?;') }}"

    # Filter allowed index creation statements (case-insensitive for WHERE)
    - name: Filter allowed index creation statements
      set_fact:
        allowed_index_creation_statements: "{{ index_creation_statements | select('match', '(?i)CREATE INDEX .*? ON `travel-sample`\..*?\..*?\(.*?\) .*? USING GSI WITH {\"defer_build\":true};') | list }}"

    - name: Debug allowed index creation statements
      debug:
        msg: "{{ allowed_index_creation_statements }}"

    # Validate Couchbase CLI availability
    - name: Validate Couchbase CLI availability
      shell: "/opt/couchbase/bin/cbq --version"
      register: cbq_check
      changed_when: false

    - name: Fail if Couchbase CLI is not available
      fail:
        msg: "Couchbase CLI is not available at /opt/couchbase/bin/cbq."
      when: cbq_check.rc != 0

    # Extract primary index names using regex
    - name: Extract primary index names using regex
      set_fact:
        primary_index_names: "{{ decoded_index_file_content | regex_findall('(?i)CREATE PRIMARY INDEX `(primary_index_\\d+)`') }}"

    - name: Debug primary index names
      debug:
        msg: "Skipping primary index creation as the following indexes were found: {{ primary_index_names }}"
      when: primary_index_names | length > 0

    # Create indexes
    - name: Create allowed indexes
      shell: "/opt/couchbase/bin/cbq -u Admin -p redhat -s '{{ item }}'"
      with_items: "{{ allowed_index_creation_statements }}"
      ignore_errors: true

    # Execute deferred_index.sh script if necessary
    - name: Check if deferred_index.sh exists
      ansible.builtin.stat:
        path: /home/ubuntu/Couchbase_UPS/deffered_index.sh
      register: deferred_script_stat

    - name: Execute deferred_index.sh script
      command: /home/ubuntu/Couchbase_UPS/deffered_index.sh
      args:
        chdir: /home/ubuntu/Couchbase_UPS
      register: script_output
      when: deferred_script_stat.stat.exists

    - name: Debug script output
      debug:
        var: script_output.stdout
      when: deferred_script_stat.stat.exists
