---
- name: Manage Couchbase indexes
  hosts: all
  become: yes
  tasks:

    # Validate index file existence
    - name: Validate index file existence
      ansible.builtin.stat:
        path: /home/ubuntu/Couchbase_UPS/index_file.txt
      register: index_file_stat

    # Read and decode index file
    - name: Read and decode index file
      ansible.builtin.slurp:
        src: /home/ubuntu/Couchbase_UPS/index_file.txt
      register: index_file_content

    - name: Decode the index file content
      set_fact:
        decoded_index_file_content: "{{ index_file_content.content | b64decode }}"

    # Extract all index creation statements with WHERE clauses
    - name: Extract index creation statements
      set_fact:
        index_creation_statements: >
          {{ decoded_index_file_content | regex_findall('(?i)CREATE INDEX .*? ON .*?\\..*?\\..*?\\(.*?\\).*?WHERE .*? USING GSI WITH {.*?defer_build.*?};') }}

    # Filter valid index creation statements
    - name: Filter valid index creation statements
      set_fact:
        valid_index_statements: "{{ index_creation_statements | list }}"

    # Debug filtered index creation statements
    - name: Debug valid index creation statements
      debug:
        msg: "{{ valid_index_statements }}"

    # Validate Couchbase CLI availability
    - name: Validate Couchbase CLI availability
      shell: "/opt/couchbase/bin/cbq --version"
      register: cbq_check
      changed_when: false

    # Create valid indexes
    - name: Create valid indexes
      shell: "/opt/couchbase/bin/cbq -u Admin -p redhat -s '{{ item }}'"
      with_items: "{{ valid_index_statements }}"
      ignore_errors: true

    # Optional: Trigger deferred builds (if applicable)
    - name: Execute deferred_index.sh script
      command: /home/ubuntu/Couchbase_UPS/deffered_index.sh
      args:
        chdir: /home/ubuntu/Couchbase_UPS
      register: script_output

    # Debug script output
    - name: Display script output
      debug:
        var: script_output.stdout
